/// Меню приложения: PilotApp.swift.
extension English {
    static let app: [(String, String)] = [
        // Вид
        ("Скрыть навигатор", "Hide Navigator"),
        ("Показать навигатор", "Show Navigator"),
        // Файл
        ("Открыть папку…", "Open Folder…"),
        ("Открыть недавний", "Open Recent"),
        ("Закрыть проект", "Close Project"),
        ("Закрыть вкладку", "Close Tab"),
        ("Закрыть другие вкладки", "Close Other Tabs"),
        ("Сохранить", "Save"),
        ("Сохранить все", "Save All"),
        // Правка
        ("Закомментировать строки", "Toggle Comment"),
        ("Показать варианты", "Show Completions"),
        ("Дублировать строку", "Duplicate Line"),
        ("Удалить строку", "Delete Line"),
        ("Строку выше", "Move Line Up"),
        ("Строку ниже", "Move Line Down"),
        ("Склеить строки", "Join Lines"),
        ("Заглавные ↔ строчные", "Toggle Case"),
        ("Перейти к строке…", "Go to Line…"),
        ("Перейти к строке", "Go to Line"),
        ("Строка или строка:столбец. В файле %@.", "Line or line:column. The file has %@."),
        ("Перейти", "Go"),
        ("Локальная история…", "Local History…"),
        ("Локальная история", "Local History"),
        ("У этого файла локальной истории не бывает", "This file has no local history"),

        // LocalHistoryView.swift
        ("отличие|отличия|отличий", "difference|differences"),
        ("Локальная история: %@", "Local History: %@"),
        ("Закрыть", "Close"),
        ("Версий пока нет", "No versions yet"),
        ("Они появятся при сохранении и когда файл поменяют снаружи",
         "They appear when you save and when the file changes outside Pilot"),
        ("до правок", "before edits"),
        ("сохранено", "saved"),
        ("изменён снаружи", "changed outside"),
        ("Версия %@ → сейчас", "Version %@ → now"),
        ("Совпадает с тем, что в редакторе", "Same as in the editor"),
        ("Восстановить эту версию", "Restore This Version"),
        ("Выберите версию", "Select a version"),
        ("Вернуть кусок из истории", "Revert Change from History"),
        ("Восстановить версию из истории", "Restore Version from History"),
        ("Строки %@–%@", "Lines %@–%@"),
        ("Вернуть кусок", "Revert"),
        ("Расширить выделение", "Expand Selection"),
        ("Сузить выделение", "Shrink Selection"),
        ("Документация", "Quick Documentation"),
        ("Параметры вызова", "Parameter Info"),
        ("Свернуть", "Fold"),
        ("Развернуть", "Unfold"),
        ("Свернуть всё", "Fold All"),
        ("Развернуть всё", "Unfold All"),
        // Поиск в файле
        ("Найти…", "Find…"),
        ("Найти и заменить…", "Find and Replace…"),
        ("Найти далее", "Find Next"),
        ("Найти ранее", "Find Previous"),
        ("Искать выделенное", "Use Selection for Find"),
        // Поиск по проекту и навигация
        ("Найти везде…", "Search Everywhere…"),
        ("Найти тип…  ⇧⇧", "Find Type…  ⇧⇧"),
        ("Структура файла…", "File Structure…"),
        ("Символ в проекте…", "Find Symbol…"),
        ("Найти в файлах…", "Find in Files…"),
        ("Следующее объявление", "Next Declaration"),
        ("Предыдущее объявление", "Previous Declaration"),
        ("Следующее вхождение", "Next Occurrence"),
        ("Предыдущее вхождение", "Previous Occurrence"),
        ("Изменённые файлы…", "Changed Files…"),
        ("Следующее изменение", "Next Change"),
        ("Предыдущее изменение", "Previous Change"),
        ("Ревью мерж-реквестов", "Review Merge Requests"),
        ("Комментировать строку…", "Comment on Line…"),
        ("Следующий тред", "Next Thread"),
        ("Предыдущий тред", "Previous Thread"),
        ("Следующий файл MR", "Next MR File"),
        ("Предыдущий файл MR", "Previous MR File"),
        ("Следующий конфликт", "Next Conflict"),
        ("Предыдущий конфликт", "Previous Conflict"),
        ("Принять текущее", "Accept Current"),
        ("Принять входящее", "Accept Incoming"),
        ("Принять оба", "Accept Both"),
        ("Отметить конфликт решённым", "Mark Conflict Resolved"),
        ("Действия в контексте…", "Context Actions…"),
        ("Перейти к объявлению", "Go to Definition"),
        ("Найти использования", "Find Usages"),
        ("Перейти к реализациям", "Go to Implementations"),
        ("Где используется ассет", "Find Asset Usages"),
        ("Исходник Markdown", "Markdown Source"),
        ("Свёрстанный Markdown", "Rendered Markdown"),
        ("Ассет ↔ .meta", "Asset ↔ .meta"),
        ("Скрыть инспектор", "Hide Inspector"),
        ("Показать инспектор", "Show Inspector"),
        ("Назад", "Back"),
        ("Вперёд", "Forward"),
        ("К последней правке", "Last Edit Location"),
        ("Недавние места…", "Recent Locations…"),
        ("Переименовать…", "Rename…"),
        ("Следующая ошибка", "Next Problem"),
        ("Предыдущая ошибка", "Previous Problem"),
        ("Следующая вкладка", "Next Tab"),
        ("Предыдущая вкладка", "Previous Tab"),
        ("Недавняя вкладка  ⌃Tab", "Recent Tab  ⌃Tab"),
        ("Крупнее", "Bigger"),
        ("Мельче", "Smaller"),
        ("Исходный размер", "Actual Size"),
        ("Подсказки в строках", "Inlay Hints"),
        ("Счётчики использований", "Usage Counts"),

        // Слитые ветки: меню
        ("Запустить «%@»", "Run “%@”"),
        ("Настроить запуск…", "Configure Run…"),
        ("Показать консоль", "Show Console"),
        ("Скрыть консоль", "Hide Console"),
        ("Панель над редактором", "Toolbar Above Editor"),
        ("Цветовая схема", "Color Scheme"),
    ]
}
