/// Форк: окна MariaDB в Docker и обозревателя базы (`Fork/Database`).
extension English {
    static let database: [(String, String)] = [
        ("DDL", "DDL"),
        ("Docker не найден", "Docker not found"),
        ("Docker не отвечает", "Docker is not responding"),
        ("LOAD DATA LOCAL INFILE не поддерживается", "LOAD DATA LOCAL INFILE is not supported"),
        ("MariaDB в Docker", "MariaDB in Docker"),
        ("MariaDB в Docker…", "MariaDB in Docker…"),
        ("База данных", "Database"),
        ("Базы", "Databases"),
        ("Выполнить", "Run"),
        ("Дамп базы (.sql или .sql.gz)", "Database dump (.sql or .sql.gz)"),
        ("Данные", "Data"),
        ("Загрузить дамп…", "Load Dump…"),
        ("Загрузка дампа…", "Loading dump…"),
        ("Запросы уходят не на эту машину — осторожнее с UPDATE и DELETE", "Queries go to another machine — careful with UPDATE and DELETE"),
        ("Запуск Colima…", "Starting Colima…"),
        ("Запуск…", "Starting…"),
        ("Запустить Colima", "Start Colima"),
        ("Запущен, база готовится…", "Running, database is initializing…"),
        ("Запущен, но база не отвечает", "Running, but the database does not respond"),
        ("Затронуто строк: %@", "Rows affected: %@"),
        ("Код выхода %@", "Exit code %@"),
        ("Контейнер MariaDB из Docker", "MariaDB container from Docker"),
        ("Контейнер", "Container"),
        ("Контейнера %@ нет", "No container %@"),
        ("Не найден хост %@", "Host %@ not found"),
        ("Не подключиться к %@:%@: %@", "Cannot connect to %@:%@: %@"),
        ("Не следить за логами", "Stop Following Logs"),
        ("Непонятный ответ сервера при входе", "Unexpected server reply during login"),
        ("Нет подключения", "Not connected"),
        ("Обозреватель базы…", "Database Browser…"),
        ("Образ", "Image"),
        ("Окружение clm-server", "clm-server environment"),
        ("Остановка…", "Stopping…"),
        ("Остановлен (%@)", "Stopped (%@)"),
        ("Отключиться", "Disconnect"),
        ("Открыть в обозревателе", "Open in Browser"),
        ("Очистить вывод", "Clear Output"),
        ("Пароль root", "Root password"),
        ("Пароль", "Password"),
        ("Перезапуск…", "Restarting…"),
        ("Подключиться", "Connect"),
        ("Подставить подключение", "Fill in a connection"),
        ("Пользователь", "User"),
        ("Порт", "Port"),
        ("Поставьте Docker Desktop, OrbStack или Colima (brew install colima docker)", "Install Docker Desktop, OrbStack or Colima (brew install colima docker)"),
        ("Проверка…", "Checking…"),
        ("Работает", "Running"),
        ("Результат %@", "Result %@"),
        ("Сделать текущей (USE)", "Make Current (USE)"),
        ("Сервер говорит не на протоколе MySQL", "The server does not speak the MySQL protocol"),
        ("Серверу нужен полный вход caching_sha2_password (TLS или RSA) — он не поддерживается", "The server requires full caching_sha2_password authentication (TLS or RSA), which is not supported"),
        ("Скопировать значение", "Copy Value"),
        ("Скопировать имя", "Copy Name"),
        ("Скопировать с заголовком", "Copy with Header"),
        ("Скопировать строки", "Copy Rows"),
        ("Следить за логами", "Follow Logs"),
        ("Соединение с сервером разорвано", "Connection to the server was lost"),
        ("Создание контейнера…", "Creating container…"),
        ("Создать и запустить", "Create and Start"),
        ("Способ входа «%@» не поддерживается — нужен mysql_native_password", "Authentication method “%@” is not supported — mysql_native_password is required"),
        ("Столбцы", "Columns"),
        ("Таблиц нет", "No tables"),
        ("Том %@ будет удалён — вернуть базу будет нельзя.", "Volume %@ will be deleted — the database cannot be recovered."),
        ("Удаление…", "Removing…"),
        ("Удалить вместе с данными", "Delete with Data"),
        ("Удалить данные…", "Delete Data…"),
        ("Удалить контейнер (данные останутся)", "Remove Container (Keep Data)"),
        ("Удалить контейнер и все данные базы?", "Remove the container and all database data?"),
        ("Удалить контейнер и данные…", "Remove Container and Data…"),
        ("Удалённый сервер", "Remote server"),
        ("Чтобы поменять, удалите контейнер — данные в томе останутся.", "To change these, remove the container — data in the volume is kept."),
        ("показаны %@ из %@", "showing %@ of %@"),
        ("⌘↩ — выделенное или весь текст", "⌘↩ — the selection or the whole text"),
        ("⌘↩ — выполнить запрос. Двойной щелчок по таблице — её строки.", "⌘↩ runs the query. Double-click a table to see its rows."),
        ("Имя базы", "Database name"),
        ("запись|записи|записей", "row|rows"),
    ]
}
