/// Git-клиент: окно git, история, ветки, stash, слияние, rebase.
extension English {
    static let git: [(String, String)] = [
        // Окно git
        ("Git — %@", "Git — %@"),
        ("История", "History"),
        ("Журнал", "Log"),
        ("Получить", "Fetch"),
        ("Обновить ветку", "Pull"),
        ("Спрятать правки и переключить", "Stash Changes and Switch"),
        ("Правки уйдут в stash, ветка переключится, и они вернутся. Если не лягут — останутся в stash.",
         "Changes go to the stash, the branch switches, and they come back. If they don’t apply, they stay in the stash."),
        ("Коммиты можно будет найти только через reflog.", "The commits will only be reachable through the reflog."),
        ("конфликтов: %@", "conflicts: %@"),
        ("Разрешить…", "Resolve…"),
        ("Пропустить коммит", "Skip Commit"),
        ("Прервать", "Abort"),
        ("Вернуть всё, как было до начала", "Put everything back as it was before"),
        ("Сначала разрешите конфликты", "Resolve the conflicts first"),
        ("Большой репозиторий", "Large repository"),
        ("Включить fsmonitor, кэш неотслеживаемых, split index и commit-graph: git status и запись индекса станут в разы быстрее и в терминале.",
         "Turn on fsmonitor, the untracked cache, split index and commit-graph: git status and index writes get several times faster, in the terminal too."),
        ("Не сейчас", "Not Now"),
        ("Ускорить", "Speed Up"),

        // Stash
        ("Что прячем (необязательно)", "What’s being stashed (optional)"),
        ("С новыми файлами", "Include new files"),
        ("Спрятать правки", "Stash Changes"),
        ("Достать (pop)", "Pop"),
        ("Применить, оставив в stash", "Apply, Keeping It Stashed"),
        ("Ничего не спрятано", "Nothing stashed"),
        ("Применить", "Apply"),
        ("Достать", "Pop"),
        ("Удалить спрятанное?", "Drop the stash?"),

        // Журнал команд
        ("Pilot ещё ничего не менял в этом репозитории", "Pilot hasn’t changed anything in this repository yet"),
        ("Код выхода: %@", "Exit code: %@"),
        ("(без вывода)", "(no output)"),
        ("Выберите команду", "Select a command"),

        // Коммит
        ("Разрешить конфликт…", "Resolve Conflict…"),
        ("Файл в конфликте", "The file has conflicts"),
        ("Amend", "Amend"),
        ("Ещё", "More"),
        ("Ничего не подготовлено — в коммит пойдут все изменения", "Nothing is staged — the commit takes all changes"),
        ("В коммит пойдёт подготовленное", "The commit takes what’s staged"),
        ("Закоммитить всё (%@)", "Commit All (%@)"),
        ("Fixup: сначала подготовьте правки", "Fixup: stage changes first"),
        ("Fixup: нет неотправленных коммитов", "Fixup: no unpushed commits"),
        ("Fixup в коммит", "Fixup into Commit"),
        ("Влить в коммит (fixup + autosquash)", "Squash into Commit (fixup + autosquash)"),
        ("%@ — без своего .meta", "%@ — without its .meta"),
        ("%@ — .meta без ассета", "%@ — .meta without its asset"),
        ("Ассет без .meta у коллег получит новый GUID, и ссылки на него порвутся; .meta без ассета Unity удалит",
         "An asset without its .meta gets a new GUID on teammates’ machines and references to it break; Unity deletes a .meta without its asset"),
        ("j/k — куски  ·  клик, ⇧клик — строки  ·  u — убрать из коммита",
         "j/k — hunks  ·  click, ⇧click — lines  ·  u — unstage"),
        ("j/k — куски  ·  клик, ⇧клик — строки  ·  s — подготовить  ·  x — откатить",
         "j/k — hunks  ·  click, ⇧click — lines  ·  s — stage  ·  x — discard"),
        ("Откатить этот кусок?", "Discard this hunk?"),
        ("Правки пропадут из файла; прежний текст останется в локальной истории (⌃⌥H).",
         "The changes leave the file; the previous text stays in local history (⌃⌥H)."),
        ("Откатить строки", "Discard Lines"),
        ("Убрать строки", "Unstage Lines"),
        ("Подготовить строки", "Stage Lines"),
        ("Откат куска", "Discarding hunk"),
        ("Fixup…", "Fixup…"),
        ("Fixup-коммит для %@", "Fixup commit for %@"),
        ("Влито в %@", "Squashed into %@"),
        ("строк выбрано: %@", "lines selected: %@"),
        ("Одной колонкой", "Unified"),
        ("Две колонки", "Side by Side"),
        ("Дифф в окне git", "Diff in Git Window"),
        ("Изменения и коммит", "Changes and Commit"),

        // Ветки
        ("Локальные", "Local"),
        ("Удалённые — недавние", "Remote — recent"),
        ("Удалённые", "Remote"),
        ("на сервере удалена", "deleted on the server"),
        ("Ветка — найти или создать", "Branch — find or create"),
        ("Найти ветку", "Find a branch"),
        ("Создать «%@»", "Create “%@”"),
        ("Получить с сервера", "Fetch from the Server"),
        ("Обновить ветку (pull)", "Pull"),
        ("Отправить (push)", "Push"),
        ("Окно git…", "Git Window…"),
        ("Новая ветка…", "New Branch…"),
        ("Сравнить", "Compare"),
        ("Влить в текущую", "Merge into Current"),
        ("Переключиться", "Check Out"),
        ("Переименовать %@", "Rename %@"),
        ("Удалить ветку %@?", "Delete branch %@?"),
        ("Только локальную; на сервере ветка останется.", "Only the local one; the branch stays on the server."),
        ("Влить %@ в %@", "Merge %@ into %@"),
        ("Перенести %@ на %@ (rebase)", "Rebase %@ onto %@"),
        ("Сравнить с %@", "Compare with %@"),
        ("История ветки", "Branch History"),
        ("Удалить…", "Delete…"),
        ("Ветки", "Branches"),
        ("Ветки…", "Branches…"),
        ("Новая ветка от %@", "New branch from %@"),
        ("Имя ветки", "Branch name"),
        ("Так ветку назвать нельзя", "That isn’t a valid branch name"),
        ("Создать", "Create"),

        // Операции
        ("Pilot: перед переключением на %@", "Pilot: before switching to %@"),
        ("Переключаюсь на %@", "Switching to %@"),
        ("Незакоммиченные правки мешают переключиться на %@.", "Uncommitted changes prevent switching to %@."),
        ("Так ветку назвать нельзя: %@", "That isn’t a valid branch name: %@"),
        ("Ветка %@ создана", "Branch %@ created"),
        ("Создаю ветку %@", "Creating branch %@"),
        ("Ветка теперь %@", "The branch is now %@"),
        ("Переименовываю", "Renaming"),
        ("Удаляю ветку %@", "Deleting branch %@"),
        ("Ветка %@ удалена", "Branch %@ deleted"),
        ("В ветке %@ есть коммиты, которых нет больше нигде. Удалить всё равно?",
         "Branch %@ has commits that exist nowhere else. Delete anyway?"),
        ("Получаю с сервера", "Fetching"),
        ("Получено", "Fetched"),
        ("Ветка обновлена", "Branch updated"),
        ("Обновляю ветку", "Pulling"),
        ("Отправляю", "Pushing"),
        ("%@ влита", "%@ merged"),
        ("Вливаю %@", "Merging %@"),
        ("Проверяю…", "Checking…"),
        ("В ветке %@ коммитов уже на сервере — rebase переписал бы их. Влейте %@ слиянием.",
         "%@ commits of this branch are already on the server — rebase would rewrite them. Merge %@ instead."),
        ("Rebase на %@", "Rebasing onto %@"),
        ("Ветка перенесена на %@", "Branch rebased onto %@"),
        ("Cherry-pick слияния не делается: непонятно, какую сторону брать",
         "Merges aren’t cherry-picked: it’s unclear which side to take"),
        ("Cherry-pick %@", "Cherry-pick %@"),
        ("Коммит %@ перенесён", "Commit %@ cherry-picked"),
        ("Revert слияния Pilot не делает", "Pilot doesn’t revert merges"),
        ("Revert %@", "Revert %@"),
        ("Коммит %@ отменён новым коммитом", "Commit %@ reverted by a new commit"),
        ("%@ — не предок текущего коммита", "%@ isn’t an ancestor of the current commit"),
        ("%@ из уходящих коммитов уже на сервере — сдвигать ветку назад нельзя",
         "%@ of the dropped commits are already on the server — the branch can’t be moved back"),
        ("Сдвигаю ветку", "Resetting the branch"),
        ("Ветка на %@, правки остались в рабочей копии", "Branch at %@, changes kept in the working tree"),
        ("Нет репозитория", "No repository"),
        ("Переписывать нечего", "Nothing to rewrite"),
        ("В диапазоне есть слияния — интерактивный rebase их развалит",
         "The range has merges — interactive rebase would flatten them"),
        ("%@ из этих коммитов уже на сервере — переписывать их нельзя",
         "%@ of these commits are already on the server — they can’t be rewritten"),
        ("Rebase", "Rebase"),
        ("История переписана", "History rewritten"),
        ("Продолжаю", "Continuing"),
        ("Прервано, всё как было", "Aborted, everything is as it was"),
        ("Прерываю", "Aborting"),
        ("Коммит пропущен", "Commit skipped"),
        ("Пропускаю коммит", "Skipping commit"),
        ("Правки спрятаны", "Changes stashed"),
        ("Прячу правки", "Stashing"),
        ("Достаю правки", "Popping"),
        ("Применяю", "Applying"),
        ("Правки возвращены", "Changes restored"),
        ("Правки применены", "Changes applied"),
        ("Спрятанное удалено", "Stash dropped"),
        ("Удаляю", "Deleting"),
        ("Ускоряю репозиторий…", "Speeding up the repository…"),
        ("Репозиторий ускорен", "Repository sped up"),
        ("git завершился с кодом %@", "git exited with code %@"),
        ("Идёт слияние", "Merge in progress"),
        ("Идёт rebase", "Rebase in progress"),
        ("Идёт cherry-pick", "Cherry-pick in progress"),
        ("Идёт revert", "Revert in progress"),
        ("Все коммиты выброшены — ветка станет пустой", "All commits are dropped — the branch would be empty"),
        ("Первый оставшийся коммит нельзя слить с предыдущим", "The first remaining commit can’t be squashed into a previous one"),

        // История
        ("git log завершился с кодом %@", "git log exited with code %@"),
        ("Текущая ветка", "Current Branch"),
        ("Все ветки", "All Branches"),
        ("Что есть в %@ и нет в %@", "What %@ has and %@ doesn’t"),
        ("файлов: %@", "files: %@"),
        ("Закрыть сравнение", "Close Comparison"),
        ("Коммитов не найдено", "No commits found"),
        ("Копировать хэш", "Copy Hash"),
        ("Новая ветка отсюда…", "New Branch from Here…"),
        ("Сравнить с текущим состоянием", "Compare with Current State"),
        ("Revert — отменить новым коммитом…", "Revert — Undo with a New Commit…"),
        ("Интерактивный rebase отсюда…", "Interactive Rebase from Here…"),
        ("Переписать коммиты после этого — только неотправленные", "Rewrite the commits after this one — unpushed only"),
        ("Сдвинуть ветку сюда", "Reset Branch to Here"),
        ("Soft — правки подготовлены", "Soft — changes staged"),
        ("Mixed — правки в рабочей копии", "Mixed — changes in the working tree"),
        ("Выберите коммит", "Select a commit"),
        ("Открыть эту версию", "Open This Version"),
        ("История файла", "File History"),
        ("Не удалось прочитать %@ в %@", "Couldn’t read %@ at %@"),
        ("слияние: файлы — против первого родителя", "merge: files against the first parent"),
        ("Отменить коммит новым коммитом?", "Undo the commit with a new commit?"),
        ("Сообщение или хэш", "Message or hash"),
        ("Автор", "Author"),
        ("%@, строки %@–%@", "%@, lines %@–%@"),
        ("История git", "Git History"),
        ("История файла или выделения", "File or Selection History"),
        ("У этого файла нет истории в git", "This file has no git history"),
        ("История строк", "Line History"),

        // Rebase
        ("Интерактивный rebase", "Interactive Rebase"),
        ("Коммиты после %@ «%@», старые сверху", "Commits after %@ “%@”, oldest first"),
        ("Новое сообщение", "New message"),
        ("p pick · r reword · s squash · f fixup · d drop · ⌥↑↓ — переставить",
         "p pick · r reword · s squash · f fixup · d drop · ⌥↑↓ — reorder"),
        ("Переписать", "Rewrite"),

        // Слияние
        ("Слияние в три колонки…", "Three-Way Merge…"),
        ("Наша версия, их и результат рядом — как в Rider", "Ours, theirs and the result side by side — as in Rider"),
        ("Слияние — %@", "Merge — %@"),
        ("Не удалось запустить UnityYAMLMerge", "Couldn’t run UnityYAMLMerge"),
        ("UnityYAMLMerge не смог слить сам:\n%@", "UnityYAMLMerge couldn’t merge on its own:\n%@"),
        ("В индексе нет версий этого файла — конфликт уже решён или файл не в слиянии",
         "The index has no versions of this file — the conflict is resolved or the file isn’t being merged"),
        ("Взять", "Take"),
        ("Править", "Edit"),
        ("Сбросить", "Reset"),
        ("Обе", "Both"),
        ("Сначала наша, потом их", "Ours first, then theirs"),
        ("Их, потом наша", "Theirs, Then Ours"),
        ("Решить автоматически", "Resolve automatically"),
        ("Все конфликты решены", "All conflicts resolved"),
        ("Нерешено: %@ из %@", "Unresolved: %@ of %@"),
        ("Решено само: %@", "Resolved automatically: %@"),
        ("Само не решается ничего", "Nothing resolves automatically"),
        ("Решить простые", "Resolve Simple"),
        ("Разница только в пробелах, вставки в одно место с обеих сторон",
         "Whitespace-only differences, insertions at the same place on both sides"),
        ("Все оставшиеся…", "All Remaining…"),
        ("Нашей версией", "With Ours"),
        ("Их версией", "With Theirs"),
        ("Взять наш файл целиком", "Take Our Whole File"),
        ("Взять их файл целиком", "Take Their Whole File"),
        ("Слить сцену или префаб по объектам — инструментом Unity", "Merge the scene or prefab by objects — with Unity’s tool"),
        ("… ещё %@ общих строк", "… %@ more common lines"),
        ("Наша версия (текущая ветка)", "Ours (current branch)"),
        ("Результат", "Result"),
        ("Их версия (вливаемая)", "Theirs (being merged)"),
        ("— файл удалён", "— file deleted"),
        ("Разрешить конфликты", "Resolve Conflicts"),
        ("Разрешить конфликты…", "Resolve Conflicts…"),
        ("Конфликтов нет", "No conflicts"),

        // Меню и редактор
        ("Получить с сервера (fetch)", "Fetch"),
        ("Подготовить изменение под курсором", "Stage Change at Caret"),
        ("Откатить изменение под курсором", "Roll Back Change at Caret"),
        ("Авторы строк (blame)", "Annotate (Blame)"),
        ("Подготовить блок", "Stage Block"),
        ("Только эти строки — в следующий коммит", "Only these lines go into the next commit"),
        ("Вернуть текст из HEAD; ⌘Z отменит", "Restore the text from HEAD; ⌘Z undoes it"),
        ("Сохранить изменения перед операцией git?", "Save changes before the git operation?"),
        ("Откат изменения", "Roll Back Change"),
        ("Не удалось получить дифф", "Couldn’t get the diff"),
        ("Этот блок уже подготовлен", "This block is already staged"),
        ("Блок подготовлен к коммиту", "Block staged for commit"),
    ]
}
