/// Git-клиент: окно git, история, ветки, stash, слияние, rebase.
extension English {
    static let git: [(String, String)] = [
        // Окно git
        ("Спрятать правки и переключить", "Stash Changes and Switch"),
        ("Правки уйдут в stash, ветка переключится, и они вернутся. Если не лягут — останутся в stash.",
         "Changes go to the stash, the branch switches, and they come back. If they don’t apply, they stay in the stash."),
        ("Коммиты можно будет найти только через reflog.", "The commits will only be reachable through the reflog."),
        ("конфликтов: %@", "conflicts: %@"),
        ("Разрешить…", "Resolve…"),
        ("Пропустить коммит", "Skip Commit"),
        ("Прервать", "Abort"),
        ("Вернуть всё, как было до начала", "Put everything back as it was before"),
        ("Сначала разрешите конфликты", "Resolve the conflicts first"),
        ("Большой репозиторий", "Large repository"),
        ("Включить fsmonitor, кэш неотслеживаемых, split index и commit-graph: git status и запись индекса станут в разы быстрее и в терминале.",
         "Turn on fsmonitor, the untracked cache, split index and commit-graph: git status and index writes get several times faster, in the terminal too."),
        ("Не сейчас", "Not Now"),
        ("Ускорить", "Speed Up"),

        // Stash
        ("Что прячем (необязательно)", "What’s being stashed (optional)"),
        ("С новыми файлами", "Include new files"),
        ("Спрятать правки", "Stash Changes"),
        ("Достать (pop)", "Pop"),
        ("Применить, оставив в stash", "Apply, Keeping It Stashed"),
        ("Ничего не спрятано", "Nothing stashed"),
        ("Применить", "Apply"),
        ("Достать", "Pop"),
        ("Удалить спрятанное?", "Drop the stash?"),

        // Журнал команд
        ("Pilot ещё ничего не менял в этом репозитории", "Pilot hasn’t changed anything in this repository yet"),
        ("Код выхода: %@", "Exit code: %@"),
        ("(без вывода)", "(no output)"),
        ("Выберите команду", "Select a command"),

        // Коммит
        ("Разрешить конфликт…", "Resolve Conflict…"),
        ("Файл в конфликте", "The file has conflicts"),
        ("Amend", "Amend"),
        ("Ничего не подготовлено — в коммит пойдут все изменения", "Nothing is staged — the commit takes all changes"),
        ("В коммит пойдёт подготовленное", "The commit takes what’s staged"),
        ("Закоммитить всё (%@)", "Commit All (%@)"),
        ("%@ — без своего .meta", "%@ — without its .meta"),
        ("%@ — .meta без ассета", "%@ — .meta without its asset"),
        ("Ассет без .meta у коллег получит новый GUID, и ссылки на него порвутся; .meta без ассета Unity удалит",
         "An asset without its .meta gets a new GUID on teammates’ machines and references to it break; Unity deletes a .meta without its asset"),
        ("j/k — куски  ·  клик, ⇧клик — строки  ·  u — убрать из коммита",
         "j/k — hunks  ·  click, ⇧click — lines  ·  u — unstage"),
        ("j/k — куски  ·  клик, ⇧клик — строки  ·  s — подготовить  ·  x — откатить",
         "j/k — hunks  ·  click, ⇧click — lines  ·  s — stage  ·  x — discard"),
        ("Откатить этот кусок?", "Discard this hunk?"),
        ("Правки пропадут из файла; прежний текст останется в локальной истории (⌃⌥H).",
         "The changes leave the file; the previous text stays in local history (⌃⌥H)."),
        ("Откатить строки", "Discard Lines"),
        ("Убрать строки", "Unstage Lines"),
        ("Подготовить строки", "Stage Lines"),
        ("Откат куска", "Discarding hunk"),
        ("Fixup…", "Fixup…"),
        ("Fixup-коммит для %@", "Fixup commit for %@"),
        ("Влито в %@", "Squashed into %@"),
        ("строк выбрано: %@", "lines selected: %@"),
        ("Одной колонкой", "Unified"),
        ("Две колонки", "Side by Side"),
        ("Изменения и коммит", "Changes and Commit"),

        // Ветки
        ("Локальные", "Local"),
        ("Удалённые — недавние", "Remote — recent"),
        ("Удалённые", "Remote"),
        ("на сервере удалена", "deleted on the server"),
        ("Ветка — найти или создать", "Branch — find or create"),
        ("Создать «%@»", "Create “%@”"),
        ("Получить с сервера", "Fetch from the Server"),
        ("Обновить ветку (pull)", "Pull"),
        ("Отправить (push)", "Push"),
        ("Влить в текущую", "Merge into Current"),
        ("Переключиться", "Check Out"),
        ("Переименовать %@", "Rename %@"),
        ("Удалить ветку %@?", "Delete branch %@?"),
        ("Только локальную; на сервере ветка останется.", "Only the local one; the branch stays on the server."),
        ("Влить %@ в %@", "Merge %@ into %@"),
        ("Перенести %@ на %@ (rebase)", "Rebase %@ onto %@"),
        ("Сравнить с %@", "Compare with %@"),
        ("Удалить…", "Delete…"),
        ("Ветки", "Branches"),
        ("Ветки…", "Branches…"),
        ("Новая ветка от %@", "New branch from %@"),
        ("Имя ветки", "Branch name"),
        ("Так ветку назвать нельзя", "That isn’t a valid branch name"),
        ("Создать", "Create"),

        // Операции
        ("Pilot: перед переключением на %@", "Pilot: before switching to %@"),
        ("Переключаюсь на %@", "Switching to %@"),
        ("Незакоммиченные правки мешают переключиться на %@.", "Uncommitted changes prevent switching to %@."),
        ("Так ветку назвать нельзя: %@", "That isn’t a valid branch name: %@"),
        ("Ветка %@ создана", "Branch %@ created"),
        ("Создаю ветку %@", "Creating branch %@"),
        ("Ветка теперь %@", "The branch is now %@"),
        ("Переименовываю", "Renaming"),
        ("Удаляю ветку %@", "Deleting branch %@"),
        ("Ветка %@ удалена", "Branch %@ deleted"),
        ("В ветке %@ есть коммиты, которых нет больше нигде. Удалить всё равно?",
         "Branch %@ has commits that exist nowhere else. Delete anyway?"),
        ("Получаю с сервера", "Fetching"),
        ("Получено", "Fetched"),
        ("Ветка обновлена", "Branch updated"),
        ("Обновляю ветку", "Pulling"),
        ("Отправляю", "Pushing"),
        ("%@ влита", "%@ merged"),
        ("Вливаю %@", "Merging %@"),
        ("Проверяю…", "Checking…"),
        ("В ветке %@ коммитов уже на сервере — rebase переписал бы их. Влейте %@ слиянием.",
         "%@ commits of this branch are already on the server — rebase would rewrite them. Merge %@ instead."),
        ("Rebase на %@", "Rebasing onto %@"),
        ("Ветка перенесена на %@", "Branch rebased onto %@"),
        ("Cherry-pick слияния не делается: непонятно, какую сторону брать",
         "Merges aren’t cherry-picked: it’s unclear which side to take"),
        ("Cherry-pick %@", "Cherry-pick %@"),
        ("Коммит %@ перенесён", "Commit %@ cherry-picked"),
        ("Revert слияния Pilot не делает", "Pilot doesn’t revert merges"),
        ("Revert %@", "Revert %@"),
        ("Коммит %@ отменён новым коммитом", "Commit %@ reverted by a new commit"),
        ("%@ — не предок текущего коммита", "%@ isn’t an ancestor of the current commit"),
        ("%@ из уходящих коммитов уже на сервере — сдвигать ветку назад нельзя",
         "%@ of the dropped commits are already on the server — the branch can’t be moved back"),
        ("Сдвигаю ветку", "Resetting the branch"),
        ("Ветка на %@, правки остались в рабочей копии", "Branch at %@, changes kept in the working tree"),
        ("Нет репозитория", "No repository"),
        ("Переписывать нечего", "Nothing to rewrite"),
        ("В диапазоне есть слияния — интерактивный rebase их развалит",
         "The range has merges — interactive rebase would flatten them"),
        ("%@ из этих коммитов уже на сервере — переписывать их нельзя",
         "%@ of these commits are already on the server — they can’t be rewritten"),
        ("Rebase", "Rebase"),
        ("История переписана", "History rewritten"),
        ("Продолжаю", "Continuing"),
        ("Прервано, всё как было", "Aborted, everything is as it was"),
        ("Прерываю", "Aborting"),
        ("Коммит пропущен", "Commit skipped"),
        ("Пропускаю коммит", "Skipping commit"),
        ("Правки спрятаны", "Changes stashed"),
        ("Прячу правки", "Stashing"),
        ("Достаю правки", "Popping"),
        ("Применяю", "Applying"),
        ("Правки возвращены", "Changes restored"),
        ("Правки применены", "Changes applied"),
        ("Спрятанное удалено", "Stash dropped"),
        ("Удаляю", "Deleting"),
        ("Ускоряю репозиторий…", "Speeding up the repository…"),
        ("Репозиторий ускорен", "Repository sped up"),
        ("git завершился с кодом %@", "git exited with code %@"),
        ("Идёт слияние", "Merge in progress"),
        ("Идёт rebase", "Rebase in progress"),
        ("Идёт cherry-pick", "Cherry-pick in progress"),
        ("Идёт revert", "Revert in progress"),
        ("Все коммиты выброшены — ветка станет пустой", "All commits are dropped — the branch would be empty"),
        ("Первый оставшийся коммит нельзя слить с предыдущим", "The first remaining commit can’t be squashed into a previous one"),

        // История
        ("git log завершился с кодом %@", "git log exited with code %@"),
        ("Текущая ветка", "Current Branch"),
        ("Все ветки", "All Branches"),
        ("Что есть в %@ и нет в %@", "What %@ has and %@ doesn’t"),
        ("файлов: %@", "files: %@"),
        ("Закрыть сравнение", "Close Comparison"),
        ("Коммитов не найдено", "No commits found"),
        ("Копировать хэш", "Copy Hash"),
        ("Новая ветка отсюда…", "New Branch from Here…"),
        ("Сравнить с текущим состоянием", "Compare with Current State"),
        ("Revert — отменить новым коммитом…", "Revert — Undo with a New Commit…"),
        ("Интерактивный rebase отсюда…", "Interactive Rebase from Here…"),
        ("Сдвинуть ветку сюда", "Reset Branch to Here"),
        ("Soft — правки подготовлены", "Soft — changes staged"),
        ("Mixed — правки в рабочей копии", "Mixed — changes in the working tree"),
        ("Выберите коммит", "Select a commit"),
        ("Открыть эту версию", "Open This Version"),
        ("История файла", "File History"),
        ("Не удалось прочитать %@ в %@", "Couldn’t read %@ at %@"),
        ("слияние: файлы — против первого родителя", "merge: files against the first parent"),
        ("Отменить коммит новым коммитом?", "Undo the commit with a new commit?"),
        ("Сообщение или хэш", "Message or hash"),
        ("Автор", "Author"),
        ("%@, строки %@–%@", "%@, lines %@–%@"),
        ("История файла или выделения", "File or Selection History"),
        ("У этого файла нет истории в git", "This file has no git history"),
        ("История строк", "Line History"),

        ("Двойной клик или Return — изменения файла в редакторе", "Double-click or Return — the file’s changes in the editor"),
        ("Открыть изменения", "Open Changes"),

        ("⌥⌘↩ — закоммитить и отправить", "⌥⌘↩ — commit and push"),

        // Панель git и строка под редактором
        ("Панель git", "Git Panel"),
        ("Панель git…", "Git Panel…"),
        ("Скрыть панель git", "Hide Git Panel"),
        ("Дифф в панели git", "Diff in Git Panel"),
        ("HEAD (текущая ветка)", "HEAD (current branch)"),
        ("Основная — по MR", "Main — by MR"),
        ("Все ветки — граф", "All branches — graph"),
        ("Ветка или тег", "Branch or tag"),
        ("Не найдено", "Not found"),
        ("Настроить строку…", "Customize Status Bar…"),
        ("Строка под редактором", "Status bar"),
        ("Перетащите, чтобы поменять порядок. Всё, что до растяжки, — слева, после — справа.",
         "Drag to reorder. Everything before the flexible space is on the left, after it — on the right."),
        ("Показаны", "Shown"),
        ("Скрыты", "Hidden"),
        ("Как было", "Restore Defaults"),
        ("Язык файла", "File language"),
        ("Число строк", "Line count"),
        ("Растяжка", "Flexible space"),
        ("Автор строки (blame)", "Line author (blame)"),
        ("Изменения и ↑↓ к серверу", "Changes and ↑↓ to the server"),
        ("Ветка git", "Git branch"),
        ("Позиция курсора", "Caret position"),
        ("Индексация и компиляция", "Indexing and compilation"),

        // Режимы истории
        ("Моя ветка", "My Branch"),
        ("По MR", "By MR"),
        ("Граф", "Graph"),
        ("Моя ветка — что в ней сверх основной; по MR — основная ветка списком влитых MR; граф — все коммиты",
         "My branch — what it has beyond the main one; by MR — the main branch as a list of merged MRs; graph — every commit"),
        ("Не нашлась основная ветка (origin/HEAD, main или master)", "No main branch found (origin/HEAD, main or master)"),
        ("HEAD отсоединён", "Detached HEAD"),
        ("Влить %@", "Merge %@"),
        ("Догнать основную ветку слиянием", "Catch up with the main branch by merging"),
        ("Перенести на %@", "Rebase onto %@"),
        ("Rebase — только если коммиты ветки ещё не отправлены", "Rebase — only while the branch’s commits aren’t pushed"),
        ("Основная ветка", "Main branch"),
        ("не отправлено: %@", "unpushed: %@"),
        ("всё отправлено", "everything pushed"),
        ("своих коммитов: %@", "own commits: %@"),
        ("от %@ %@", "off %@ %@"),
        ("%@ ушла вперёд на %@", "%@ is ahead by %@"),
        ("%@ не ушла вперёд", "%@ hasn’t moved"),
        ("Незакоммиченные изменения: %@", "Uncommitted changes: %@"),
        ("к коммиту →", "to commit →"),
        ("Неотправленных коммитов нет", "No unpushed commits"),
        ("Своих коммитов нет — ветка совпадает с %@", "No own commits — the branch matches %@"),
        ("отходит от %@:", "branches off %@:"),
        ("Другие мои ветки", "My Other Branches"),
        ("Коммитов сверх %@", "Commits beyond %@"),
        ("На сколько %@ ушла вперёд", "How far %@ has moved ahead"),
        ("%@ влита в ветку", "%@ merged into the branch"),
        ("Ещё не на сервере", "Not on the server yet"),
        ("Уже на сервере", "Already on the server"),
        ("влита %@", "merged %@"),
        ("обратных слияний скрыто: %@", "back-merges hidden: %@"),
        ("Открыть MR в ревью", "Open the MR in Review"),
        ("MR !%@ не найден — нет доступа к GitLab?", "MR !%@ not found — no access to GitLab?"),

        // Rebase
        ("Интерактивный rebase", "Interactive Rebase"),
        ("Коммиты после %@ «%@», старые сверху", "Commits after %@ “%@”, oldest first"),
        ("Новое сообщение", "New message"),
        ("p pick · r reword · s squash · f fixup · d drop · ⌥↑↓ — переставить",
         "p pick · r reword · s squash · f fixup · d drop · ⌥↑↓ — reorder"),
        ("Переписать", "Rewrite"),

        // Слияние
        ("Слияние в три колонки…", "Three-Way Merge…"),
        ("Наша версия, их и результат рядом — как в Rider", "Ours, theirs and the result side by side — as in Rider"),
        ("Слияние — %@", "Merge — %@"),
        ("Не удалось запустить UnityYAMLMerge", "Couldn’t run UnityYAMLMerge"),
        ("UnityYAMLMerge не смог слить сам:\n%@", "UnityYAMLMerge couldn’t merge on its own:\n%@"),
        ("В индексе нет версий этого файла — конфликт уже решён или файл не в слиянии",
         "The index has no versions of this file — the conflict is resolved or the file isn’t being merged"),
        ("Решено само: %@", "Resolved automatically: %@"),
        ("Само не решается ничего", "Nothing resolves automatically"),
        ("Решить простые", "Resolve Simple"),
        ("Разница только в пробелах, вставки в одно место с обеих сторон",
         "Whitespace-only differences, insertions at the same place on both sides"),
        ("Слить сцену или префаб по объектам — инструментом Unity", "Merge the scene or prefab by objects — with Unity’s tool"),
        ("Результат", "Result"),
        ("— файл удалён", "— file deleted"),
        ("Разрешить конфликты", "Resolve Conflicts"),
        ("Разрешить конфликты…", "Resolve Conflicts…"),
        ("Конфликтов нет", "No conflicts"),

        // Окно слияния, как в Rider
        ("В нерешённых кусках останется текст общего предка.", "Unresolved chunks keep the common ancestor’s text."),
        ("В нерешённых спорах останется наша сторона.", "Unresolved conflicts keep our side."),
        ("Весь файл — их версией", "The whole file from theirs"),
        ("Весь файл — нашей версией", "The whole file from ours"),
        ("Все — их", "All Theirs"),
        ("Все — наши", "All Ours"),
        ("Записать результат и отметить файл решённым", "Write the result and mark the file resolved"),
        ("Изменений: %@ · конфликтов: %@, нерешено: %@", "Changes: %@ · conflicts: %@, unresolved: %@"),
        ("Их версия", "Theirs"),
        ("Их", "Theirs"),
        ("Их: %@", "Theirs: %@"),
        ("Наша: %@", "Ours: %@"),
        ("Наше", "Ours"),
        ("Не все конфликты решены", "Not all conflicts are resolved"),
        ("По объектам — споры по свойствам GameObject'ов и компонентов; текстом — три колонки, как для кода",
         "By objects — conflicts per property of GameObjects and components; as text — three columns, as for code"),
        ("По объектам", "By Objects"),
        ("Принять левое", "Accept Left"),
        ("Принять правое", "Accept Right"),
        ("Слито само: %@ · споров: %@, нерешено: %@", "Merged automatically: %@ · conflicts: %@, unresolved: %@"),
        ("Слито само: %@ наших правок и %@ их", "Merged automatically: %@ of our changes and %@ of theirs"),
        ("Сохранить как есть", "Save As Is"),
        ("Споров нет — всё слилось по объектам само", "No conflicts — everything merged by objects on its own"),
        ("Текстом", "As Text"),
        ("объект удалён у нас, у них изменён", "object deleted in ours, changed in theirs"),
        ("объект удалён у них, у нас изменён", "object deleted in theirs, changed in ours"),
        ("— удалено —", "— deleted —"),
        ("Двоичный файл — слить его нельзя, только взять одну версию целиком", "A binary file can’t be merged — take one version whole"),
        ("Взять нашу: %@", "Take Ours: %@"),
        ("Взять их: %@", "Take Theirs: %@"),

        // Версии картинок и моделей
        ("До", "Before"),
        ("На диске", "On Disk"),
        ("Наложением", "Overlay"),
        ("Подготовлено", "Staged"),
        ("Рядом", "Side by Side"),
        ("Файла не было", "No file yet"),

        // Меню и редактор
        ("Получить с сервера (fetch)", "Fetch"),
        ("Подготовить изменение под курсором", "Stage Change at Caret"),
        ("Откатить изменение под курсором", "Roll Back Change at Caret"),
        ("Авторы строк (blame)", "Annotate (Blame)"),
        ("Подготовить блок", "Stage Block"),
        ("Только эти строки — в следующий коммит", "Only these lines go into the next commit"),
        ("Вернуть текст из HEAD; ⌘Z отменит", "Restore the text from HEAD; ⌘Z undoes it"),
        ("Сохранить изменения перед операцией git?", "Save changes before the git operation?"),
        ("Откат изменения", "Roll Back Change"),
        ("Не удалось получить дифф", "Couldn’t get the diff"),
        ("Этот блок уже подготовлен", "This block is already staged"),
        ("Блок подготовлен к коммиту", "Block staged for commit"),
    ]
}
