/// Модель: Workspace и его расширения, команды и сочетания, поиск, палитра,
/// переименование, FBX, медиа, Markdown; TextBuffer.
extension English {
    static let model: [(String, String)] = [
        // Числа (Workspace.swift, тесты)
        ("файл|файла|файлов", "file|files"),
        ("вхождение|вхождения|вхождений", "occurrence|occurrences"),
        ("файле|файлах|файлах", "file|files"),

        // FBX.swift
        ("Не FBX: нет ни двоичного заголовка, ни текстовых записей", "Not an FBX file: no binary header and no text records"),
        ("FBX повреждён: записи выходят за конец файла", "The FBX file is corrupted: records run past the end of the file"),
        ("FBX %@.%@ не поддерживается — нужен 7.x", "FBX %@.%@ isn’t supported — version 7.x is required"),
        ("Сжатые массивы FBX здесь не распаковать", "Compressed FBX arrays can’t be unpacked here"),

        // Keymap.swift — команды
        ("Открыть папку", "Open Folder"),
        ("Найти в файле", "Find in File"),
        ("Найти и заменить", "Find and Replace"),
        ("Найти везде", "Search Everywhere"),
        ("Найти тип (кроме ⇧⇧)", "Find Type (besides ⇧⇧)"),
        ("Структура файла", "File Structure"),
        ("Символ в проекте", "Symbol in Project"),
        ("Найти в файлах", "Find in Files"),
        ("Изменённые файлы", "Changed Files"),
        ("Недавние места", "Recent Locations"),
        ("Действия в контексте", "Context Actions"),
        ("Переименовать", "Rename"),
        ("Недавняя вкладка (кроме ⌃Tab)", "Recent Tab (besides ⌃Tab)"),
        ("Навигатор", "Navigator"),
        ("Инспектор Unity", "Unity Inspector"),
        ("Шрифт крупнее", "Increase Font Size"),
        ("Шрифт мельче", "Decrease Font Size"),
        ("Исходный размер шрифта", "Reset Font Size"),
        ("Комментировать строку", "Comment on Line"),
        // Keymap.swift — разделы
        ("Файл", "File"),
        ("Правка", "Edit"),
        ("Поиск в файле", "Find in File"),
        ("Поиск по проекту", "Search Project"),
        ("Навигация", "Navigation"),
        ("Вкладки и вид", "Tabs and View"),
        ("Git, ревью, конфликты", "Git, Reviews, Conflicts"),
        ("Другое", "Other"),

        // Markdown.swift
        ("Заметка", "Note"),
        ("Совет", "Tip"),
        ("Важно", "Important"),
        ("Внимание", "Warning"),
        ("Осторожно", "Caution"),

        // MediaKind.swift
        ("Изображение", "Image"),
        ("3D-модель", "3D Model"),
        ("Шрифт", "Font"),

        // PaletteItem.swift
        ("Метод, свойство, поле…", "Method, property, field…"),
        ("Использования", "Usages"),
        ("Одноимённые объявления — уточните", "Declarations with this name — pick one"),
        ("Реализации и наследники", "Implementations and subclasses"),
        ("Изменённый файл…", "Changed file…"),
        ("Недавнее место…", "Recent location…"),

        // Rename.swift
        ("Имя пустое", "The name is empty"),
        ("Имя начинается с буквы или _", "A name must start with a letter or _"),
        ("В имени только буквы, цифры и _", "A name may contain only letters, digits, and _"),
        ("«%@» — ключевое слово; как имя — только @%@", "“%@” is a keyword; as a name, use @%@"),

        // UnifiedSearch.swift
        ("Всё", "All"),
        ("Файлы", "Files"),
        ("Типы", "Types"),
        ("Символы", "Symbols"),
        ("Текст", "Text"),
        ("Файл, класс, символ или текст…", "File, class, symbol, or text…"),
        ("Перейти к файлу…", "Go to file…"),
        ("Класс, интерфейс, структура…", "Class, interface, struct…"),
        ("Текст в файлах проекта…", "Text in project files…"),

        // Workspace+Conflicts.swift
        ("В файле ещё остались конфликты", "The file still has conflicts"),

        // Workspace+ContextActions.swift
        ("Перейти по ссылке", "Open Link"),
        ("Конфликт слияния", "Merge Conflict"),
        ("Строка %@", "Line %@"),
        ("Искать «%@» в проекте", "Search Project for “%@”"),
        ("Показать обсуждение", "Show Discussion"),
        ("Что было до изменения", "Show Original Text"),
        ("Показать IL метода", "Show Method IL"),
        ("Открыть ассет", "Open Asset"),
        ("Открыть .meta", "Open .meta"),

        // Workspace.swift
        ("Проект", "Project"),
        ("Недавние проекты", "Recent Projects"),
        ("Открыть", "Open"),
        ("Выберите папку проекта или архив: APK, AAB, JAR, AAR, DEX", "Choose a project folder or an archive: APK, AAB, JAR, AAR, DEX"),
        ("%@ изменён на диске — несохранённые правки остались в редакторе", "%@ changed on disk — your unsaved edits are still in the editor"),
        ("открыт", "open"),
        ("сборка", "assembly"),
        ("текст", "text"),
        ("правка", "edit"),
        ("Объявление не найдено: Rustlyn ещё компилирует проект", "Declaration not found: Rustlyn is still compiling the project"),
        ("Объявление не найдено: проект ещё не скомпилирован", "Declaration not found: the project isn’t compiled yet"),
        ("Объявление не найдено", "Declaration not found"),
        ("Объявление знает языковой сервер — он ещё запускается%@", "The language server knows the declaration — it’s still starting%@"),
        ("Объявление не найдено: языковой сервер не работает — %@", "Declaration not found: the language server isn’t running — %@"),
        ("Rustlyn ещё компилирует проект — ищу по тексту", "Rustlyn is still compiling the project — searching the text instead"),
        ("Сначала откройте ассет", "Open an asset first"),
        ("Нет файла %@", "No file %@"),
        ("Это версия файла из мерж-реквеста — она только для чтения", "This is the merge request’s version of the file — it’s read-only"),
        ("Текст уже другой — правка не применена", "The text has changed — the edit wasn’t applied"),
        ("Переименование пока только для C#", "Rename is only available for C# for now"),
        ("Rustlyn ещё компилирует проект — переименование будет через несколько секунд", "Rustlyn is still compiling the project — rename will be available in a few seconds"),
        ("Переименовать «%@»", "Rename “%@”"),
        ("Так назвать нельзя", "That name isn’t allowed"),
        ("Переименование «%@»", "Rename “%@”"),
        ("Файл %@ уже есть — имя файла осталось прежним", "%@ already exists — the file name was left unchanged"),
        ("Не удалось переименовать файл: %@", "Couldn’t rename the file: %@"),
        ("Не удалось сохранить «%@»", "Couldn’t save “%@”"),
        ("Сохранить изменения в «%@»?", "Save changes to “%@”?"),
        ("Сохранить изменения в %@?", "Save changes to %@?"),
        ("Если не сохранить, правки пропадут.", "Your changes will be lost if you don’t save them."),
        ("Не сохранять", "Don’t Save"),

        // TextBuffer.swift
        ("Изменение на диске", "Change on Disk"),

        // Слитые ветки: запуск, отладка, пара, переименование
        ("«%@» → «%@»: %@ в %@", "“%@” → “%@”: %@ in %@"),
        ("%@. Пропущены — текст ушёл от компиляции: %@", "%@. Skipped — the text changed since compilation: %@"),
        ("Все перегрузки", "All overloads"),
        ("И в комментариях и строках", "In comments and strings too"),
        ("И файл — вслед за типом", "The file too — to match the type"),
        ("Во второй половине пары", "In the other half of the pair"),
        ("Датаграмма…", "Datagram…"),
        ("Зеркальный файл…", "Mirrored file…"),
        ("Показать файл в дереве", "Reveal File in Tree"),
        ("Новое окно", "New Window"),
        ("Запустить", "Run"),
        ("Остановить", "Stop"),
        ("Консоль", "Console"),
        ("Начать отладку", "Start Debugging"),
        ("Остановить отладку", "Stop Debugging"),
        ("Продолжить", "Continue"),
        ("Приостановить", "Pause"),
        ("Шаг с обходом", "Step Over"),
        ("Шаг с заходом", "Step Into"),
        ("Шаг с выходом", "Step Out"),
        ("Точка останова", "Toggle Breakpoint"),
        ("Убрать все точки останова", "Remove All Breakpoints"),
        ("Парный проект", "Paired Project"),
        ("Двойник в паре", "Counterpart in Pair"),
        ("Искать и в паре", "Search in Pair Too"),
        ("Сверка датаграмм", "Datagram Contract"),
        ("Расхождения зеркал", "Mirror Drift"),
        ("Запуск", "Run"),
        ("Отладка", "Debug"),
        ("Пара", "Pair"),
    ]
}
