/// Окно NuGet: пакеты проектов, поиск на nuget.org, установка через dotnet.
extension English {
    static let nuget: [(String, String)] = [
        // Числа
        ("обновление|обновления|обновлений", "update|updates"),
        ("проект|проекта|проектов", "project|projects"),

        // PilotApp.swift, Keymap.swift
        ("Пакеты NuGet…", "NuGet Packages…"),
        ("Пакеты NuGet", "NuGet Packages"),

        // NuGetService.swift
        ("Установленные", "Installed"),
        ("Обновления", "Updates"),
        ("Поиск", "Search"),
        ("Установка %@ %@", "Installing %@ %@"),
        ("Установка %@", "Installing %@"),
        ("Удаление %@", "Removing %@"),
        ("Обновление пакетов", "Updating packages"),
        ("%@: готово", "%@: done"),
        ("Не найден dotnet — установите .NET SDK", "dotnet not found — install the .NET SDK"),
        ("%@: отменено", "%@: cancelled"),
        ("%@: ошибка, код %@", "%@: failed with code %@"),

        // NuGetWindow.swift
        ("NuGet — %@", "NuGet — %@"),
        ("Проект этого окна закрыт", "This window’s project is closed"),
        ("Искать на nuget.org", "Search nuget.org"),
        ("Фильтр по имени", "Filter by name"),
        ("Предварительные", "Prerelease"),
        ("Показывать и предлагать версии с меткой: -beta, -rc, -preview",
         "Show and suggest labeled versions: -beta, -rc, -preview"),
        ("Перечитать проекты", "Reload Projects"),
        ("Обновить все", "Update All"),
        ("Не удалось спросить nuget.org", "Couldn’t reach nuget.org"),
        ("Ничего не нашлось", "Nothing found"),
        ("Нет проектов .NET в SDK-стиле", "No SDK-style .NET projects"),
        ("Проекты Unity генерирует редактор — пакеты NuGet в них не ставят",
         "Unity projects are generated by the editor — NuGet packages aren’t installed into them"),
        ("Проверяю обновления…", "Checking for updates…"),
        ("Всё свежее", "Everything is up to date"),
        ("Пакетов пока нет", "No packages yet"),
        ("Найдите их на вкладке «Поиск»", "Find some on the Search tab"),
        ("Выберите пакет", "Select a package"),
        ("Отменить", "Cancel"),
        ("Вывод dotnet", "dotnet Output"),
        ("В проектах разные версии", "Projects use different versions"),
        ("Префикс имени подтверждён владельцем", "Name prefix verified by the owner"),
        ("Уже установлен", "Already installed"),
        ("Сайт", "Website"),
        ("Версия", "Version"),
        ("Всем — %@", "All to %@"),
        ("Поставить эту версию во все проекты, где пакет уже есть",
         "Use this version in every project that already has the package"),
        ("Установить во все", "Install in All"),
        ("Проекты", "Projects"),
        ("Версия из Directory.Packages.props", "Version from Directory.Packages.props"),
        ("Обновить до %@", "Update to %@"),
        ("Сменить на %@", "Change to %@"),
        ("Удалить из %@", "Remove from %@"),
        ("Установить", "Install"),
    ]
}
