/// Сервисы и их вьюхи: Unity, GitLab, Git, LSP, архивы, сборки, Rustlyn,
/// медиа-просмотр, CodeView, всплывающие подсказки.
extension English {
    static let services: [(String, String)] = [
        // UnityService.swift
        ("Объекта &%@ в этом файле нет", "There is no object &%@ in this file"),
        ("Встроенный ресурс Unity — в проекте его нет", "Built-in Unity resource — it isn’t in the project"),
        ("Индекс ассетов ещё строится…", "The asset index is still being built…"),
        ("Ассет %@ не найден — битая ссылка", "Asset %@ not found — broken reference"),
        ("Это не Unity-проект", "This is not a Unity project"),
        ("Индекс ассетов ещё строится — попробуйте через секунду",
         "The asset index is still being built — try again in a second"),
        ("У файла нет .meta — Unity о нём не знает", "The file has no .meta — Unity doesn’t know about it"),
        ("Сообщение Unity — вызывает движок", "Unity message — called by the engine"),
        ("Сериализуется — видно в инспекторе", "Serialized — visible in the inspector"),
        ("Встроенный ресурс Unity", "Built-in Unity resource"),
        ("%@\n⌘B или ⌘+клик — открыть", "%@\n⌘B or ⌘-click to open"),
        ("Ассета с таким GUID в проекте нет — битая ссылка (Missing)",
         "No asset with this GUID in the project — broken reference (Missing)"),
        ("%@ из вложенного префаба", "%@ from a nested prefab"),
        ("→ %@\n⌘B — перейти", "→ %@\n⌘B to go there"),
        // UnityInspectorView.swift
        ("Поставьте курсор на объект сцены, префаба или ассета",
         "Place the cursor on an object in a scene, prefab or asset"),
        ("Отладка", "Debug"),
        ("Отладка: показать служебные поля, как Debug-инспектор Unity",
         "Debug: show internal fields, like Unity’s Debug inspector"),
        ("Активность", "Active State"),
        ("Переименование", "Rename"),
        ("Тег", "Tag"),
        ("Слой", "Layer"),
        ("Префаб", "Prefab"),
        ("Скрипт", "Script"),
        ("Дети · %@", "Children · %@"),
        ("Включение компонента", "Enable Component"),
        ("Показать в тексте", "Show in text"),
        ("Открыть скрипт", "Open script"),
        ("Нет полей", "No fields"),
        ("%@… (%@ симв.)", "%@… (%@ chars)"),
        ("Многострочные и очень длинные значения правятся в тексте",
         "Multiline and very long values are edited in the text"),
        ("Поворот", "Rotation"),
        ("Встроенный ресурс", "Built-in resource"),
        ("Ассета с GUID %@ в проекте нет", "No asset with GUID %@ in the project"),
        // UnityInspector.swift
        ("Переопределения", "Overrides"),
        // GitLabClient.swift
        ("GitLab не принял токен — возможно, он отозван или истёк",
         "GitLab rejected the token — it may have been revoked or expired"),
        ("Нет прав: %@", "Permission denied: %@"),
        ("Не найдено — проект или MR недоступны с этим токеном",
         "Not found — the project or MR is not accessible with this token"),
        ("GitLab ответил %@: %@", "GitLab responded %@: %@"),
        ("Нет связи с GitLab: %@", "Can’t reach GitLab: %@"),
        ("Непонятный ответ GitLab: %@", "Unexpected response from GitLab: %@"),
        ("неверный адрес %@", "invalid address %@"),
        ("нет ответа", "no response"),
        // ReviewService.swift
        ("Откройте проект", "Open a project"),
        ("У репозитория нет remote на GitLab", "The repository has no GitLab remote"),
        ("Открытые", "Open"),
        ("Жду моего ревью", "Awaiting My Review"),
        ("Мои", "Mine"),
        ("Остальные", "Others"),
        ("MR !%@ не найден", "MR !%@ not found"),
        ("У MR нет версии для сравнения — возможно, в нём ещё нет коммитов",
         "The MR has no version to compare — it may have no commits yet"),
        // TokenStore.swift
        ("код %@", "code %@"),
        ("Не удалось сохранить токен в связке ключей: %@", "Couldn’t save the token to the keychain: %@"),
        // GitService.swift
        ("Файл не в git-репозитории", "The file is not in a git repository"),
        ("Не удалось запустить git", "Couldn’t run git"),
        ("git add завершился с кодом %@", "git add exited with code %@"),
        // GitParsing.swift
        ("изменён", "modified"),
        ("добавлен", "added"),
        ("удалён", "deleted"),
        ("переименован", "renamed"),
        ("не отслеживается", "untracked"),
        ("конфликт", "conflict"),
        ("без коммитов", "no commits"),
        // LSPService.swift, LSPClient.swift, JSONRPC.swift
        ("запускается", "starting"),
        ("инициализация", "initializing"),
        ("не найден исполняемый файл %@", "executable %@ not found"),
        ("сервер завершился с кодом %@", "the server exited with code %@"),
        ("неизвестная ошибка", "unknown error"),
        ("Некорректный ответ LSP: %@", "Malformed LSP response: %@"),
        ("Таймаут запроса %@", "Request %@ timed out"),
        ("Языковой сервер не запущен", "The language server is not running"),
        ("Запрос отменён", "Request cancelled"),
        ("получен null вместо %@", "got null instead of %@"),
        // JadxClient.swift
        ("jadx завершился (код %@)", "jadx exited (code %@)"),
        ("jadx: неожиданный ответ на %@", "jadx: unexpected response to %@"),
        ("jadx не ответил", "jadx did not respond"),
        ("Pilot собран без jadx: нужен JDK (brew install openjdk) и пересборка",
         "Pilot was built without jadx: it needs a JDK (brew install openjdk) and a rebuild"),
        ("Не найдена Java для jadx: brew install openjdk", "Java for jadx not found: brew install openjdk"),
        // ArchiveService.swift
        ("В архиве нет %@", "%@ is not in the archive"),
        ("Архив не открыт", "The archive is not open"),
        ("Архив закрыт", "The archive is closed"),
        ("Переходы есть только в коде классов", "Navigation works only in class code"),
        ("Здесь нет имени", "There is no name here"),
        ("Объявление не в этом архиве — например, в Android SDK",
         "The declaration isn’t in this archive — e.g. it’s in the Android SDK"),
        // AssemblySource.swift
        ("// Типов верхнего уровня: %@. Из метаданных видны объявления,",
         "// Top-level types: %@. Metadata shows declarations;"),
        ("// тела методов в C# не восстанавливаются.", "// C# method bodies are not recovered."),
        // AssemblyMetadata.swift
        ("Нативная библиотека: .NET-метаданных в ней нет", "Native library: it has no .NET metadata"),
        ("Не удалось прочитать сборку: %@", "Couldn’t read the assembly: %@"),
        ("нет потока таблиц", "no tables stream"),
        ("таблицы не помещаются в файл", "the tables don’t fit in the file"),
        // RustlynTypes.swift
        ("проект|проекта|проектов", "project|projects"),
        ("сборки|сборок|сборок", "assembly|assemblies"),
        ("Unity без .csproj", "Unity without .csproj"),
        ("папка без .csproj", "folder without .csproj"),
        ("из кэша", "from cache"),
        ("%@ с", "%@ s"),
        ("%@ против %@ · %@ · %@", "%@ against %@ · %@ · %@"),
        // MediaViews.swift
        ("Вписать в окно", "Zoom to Fit"),
        ("Реальный размер", "Actual Size"),
        ("Картинку не прочитать", "Can’t read the image"),
        ("кадр|кадра|кадров", "frame|frames"),
        ("альфа", "alpha"),
        ("Шрифт не прочитать", "Can’t read the font"),
        ("Свой текст для образца", "Custom sample text"),
        ("Символы (%@)", "Glyphs (%@)"),
        ("глиф|глифа|глифов", "glyph|glyphs"),
        ("Латиница", "Latin"),
        ("Кириллица", "Cyrillic"),
        ("Цифры", "Digits"),
        ("Каркас", "Wireframe"),
        ("В файле нет геометрии — только кости или анимация",
         "The file has no geometry — only bones or animation"),
        ("Этот формат модели не прочитать", "Can’t read this model format"),
        ("В файле нет геометрии", "The file has no geometry"),
        ("сетка|сетки|сеток", "mesh|meshes"),
        ("треугольник|треугольника|треугольников", "triangle|triangles"),
        ("вершина|вершины|вершин", "vertex|vertices"),
        ("материал|материала|материалов", "material|materials"),
        ("кость|кости|костей", "bone|bones"),
        ("анимация|анимации|анимаций", "animation|animations"),
        ("%@ м", "%@ m"),
        // CodeView.swift
        ("Файл слишком большой (%@)", "The file is too large (%@)"),
        ("Бинарный файл — предпросмотр недоступен", "Binary file — no preview available"),
        ("Не удалось прочитать файл: %@", "Couldn’t read the file: %@"),
        ("нет доступа к файлу", "no access to the file"),
        ("нет использований", "no usages"),
        ("использование|использования|использований", "usage|usages"),
        ("Сообщение Unity", "Unity message"),
        // InfoPopup.swift
        ("в %@", "in %@"),
        ("Возвращает: ", "Returns: "),
        // Copilot
        ("Copilot не выдал код для входа", "Copilot didn’t provide a sign-in code"),
        ("Введите код на странице GitHub — он уже в буфере обмена:", "Enter the code on the GitHub page — it’s already on the clipboard:"),
        ("Войти через GitHub…", "Sign In with GitHub…"),
        ("Вход выполнен", "Signed in"),
        ("Вход выполнен: %@", "Signed in as %@"),
        ("Выйти", "Sign Out"),
        ("Жду подтверждения…", "Waiting for confirmation…"),
        ("Запускается", "Starting"),
        ("Не выполнен вход в GitHub", "Not signed in to GitHub"),
        ("Не удалось распаковать сервер Copilot", "Couldn’t unpack the Copilot server"),
        ("Не удалось скачать сервер Copilot: %@", "Couldn’t download the Copilot server: %@"),
        ("Подсказка Copilot", "Copilot Suggestion"),
        ("Подсказки Copilot в коде", "Copilot suggestions in code"),
        ("Сервер Copilot скачался с другой контрольной суммой — не запускаю", "The downloaded Copilot server has a different checksum — not running it"),
        ("Серый текст у курсора: Tab — принять, Esc — убрать. Нужна подписка GitHub Copilot.", "Gray text at the cursor: Tab to accept, Esc to dismiss. Requires a GitHub Copilot subscription."),
        ("Скачиваю сервер Copilot", "Downloading the Copilot server"),
        ("Скопировать код и открыть GitHub", "Copy Code and Open GitHub"),
        ("У аккаунта GitHub нет подписки Copilot", "This GitHub account has no Copilot subscription"),
    ]
}
