/// Настройки: PilotApp.swift, LanguageSettings.swift, KeymapSettings.swift.
extension English {
    static let settings: [(String, String)] = [
        ("Общие", "General"),
        ("Сочетания клавиш", "Key Bindings"),
        // Язык
        ("Язык интерфейса", "Interface language"),
        ("Как в системе — %@", "System default — %@"),
        ("Системные меню и диалоги macOS сменят язык после перезапуска Pilot.",
         "Standard macOS menus and dialogs switch language after Pilot restarts."),
        // Сочетания клавиш
        ("Команда или сочетание", "Command or shortcut"),
        ("Сбросить всё", "Reset All"),
        ("Показать keybindings.json в Finder — его можно править руками и носить с собой",
         "Show keybindings.json in Finder — you can edit it by hand and take it with you"),
        ("⇧⇧, ⌃Tab, ⌃- / ⌃⇧- и боковые кнопки мыши работают всегда, в дополнение к назначенному.",
         "⇧⇧, ⌃Tab, ⌃- / ⌃⇧- and the side mouse buttons always work, in addition to what is assigned."),
        ("«%@»", "“%@”"),
        ("То же сочетание у %@ — сработает одно из них", "%@ has the same shortcut — only one of them will fire"),
        ("Нажмите сочетание…", "Press shortcut…"),
        ("Клик — записать новое сочетание; ⌫ — убрать, ⎋ — отменить",
         "Click to record a new shortcut; ⌫ removes it, ⎋ cancels"),
        ("без сочетания", "no shortcut"),
        ("Вернуть: %@", "Restore: %@"),
        ("%@ уже у «%@»", "%1$@ is already used by “%2$@”"),
        ("Забрать сочетание у той команды или оставить у обеих? С двумя сработает только одна.",
         "Take the shortcut from that command or keep it on both? With two, only one will fire."),
        ("Забрать", "Take It"),
        ("Оставить у обеих", "Keep on Both"),
        ("Отмена", "Cancel"),

        // Слитые ветки: настройки
        ("Оформление", "Appearance"),
        ("Импорт из Rider…", "Import from Rider…"),
        ("Сочетания, размер шрифта и счётчики использований из settings.zip или папки настроек Rider", "Shortcuts, font size and usage counters from a Rider settings.zip or settings folder"),
        ("Окно", "Window"),
        ("Верхняя панель", "Top Bar"),
        ("Обычная", "Regular"),
        ("Компактная", "Compact"),
        ("Путь к файлу над редактором", "File path above the editor"),
        ("Вкладки проектов", "Project tabs"),
        ("Проекты открываются вкладками одного окна; полоса с названиями — когда их больше одного. Выключено — каждый проект в своём окне, а вторая половина пары — вкладкой по своей кнопке.", "Projects open as tabs of one window; the bar with their names appears when there’s more than one. Off — each project gets its own window, and the other half of a pair opens as a tab from its button."),
        ("Кнопки на панели", "Toolbar buttons"),
        ("Настроить…", "Customize…"),
        // Настройки → Кэши: CacheSettingsView.swift, CacheStore.swift
        ("Кэши", "Caches"),
        ("Кэши Pilot: %@", "Pilot caches: %@"),
        ("Ещё %@ — история правок", "Plus %@ of local history"),
        ("Считаю…", "Calculating…"),
        ("Удалять кэши проектов, которые не открывали", "Remove caches of projects not opened for"),
        ("Никогда", "Never"),
        ("30 дней", "30 days"),
        ("90 дней", "90 days"),
        ("180 дней", "180 days"),
        ("Удалить устаревшие (%@)", "Remove Stale (%@)"),
        ("Проекты, которых нет на диске или которые не открывали %@ дней", "Projects that are gone from disk or were not opened for %@ days"),
        ("Очистить все кэши…", "Clear All Caches…"),
        ("Кэш ускоряет открытие проекта, поиск и навигацию. Удалённый кэш проект соберёт заново, когда его откроют. Кэши открытых проектов не удаляются.", "Caches speed up opening a project, search and navigation. A removed cache is rebuilt the next time the project is opened. Caches of open projects are not removed."),
        ("Кэшей проектов нет", "No project caches"),
        ("История правок", "Local History"),
        ("Не кэш: прежние версии файлов, которые Pilot сохранял при правке. Удалённую историю не вернуть.", "Not a cache: earlier versions of files Pilot kept while you edited. Removed history cannot be restored."),
        ("Пересчитать", "Recalculate"),
        ("Удалить историю правок «%@»?", "Remove local history of “%@”?"),
        ("Удалить", "Remove"),
        ("Прежние версии файлов этого проекта пропадут насовсем.", "Earlier versions of this project's files will be gone for good."),
        ("Очистить все кэши (%@)?", "Clear all caches (%@)?"),
        ("Проекты соберут кэши заново при следующем открытии — первый раз это дольше обычного. История правок останется.", "Projects rebuild their caches the next time they open, which takes longer that first time. Local history stays."),
        ("Проект открыт — закройте его, чтобы удалить", "The project is open — close it to remove"),
        ("нет на диске", "gone from disk"),
        ("путь неизвестен", "path unknown"),
        ("общие для всех проектов", "shared by all projects"),
        ("ускоряет запуск декомпилятора", "speeds up starting the decompiler"),
        ("изменён %@", "modified %@"),
        ("Разобранные сборки .NET", "Parsed .NET assemblies"),
        ("Архив классов jadx", "jadx class archive"),
        ("Старые версии сервера Copilot", "Old Copilot server versions"),
        ("Проекты, которых Pilot не помнит (%@)", "Projects Pilot no longer remembers (%@)"),
    ]
}
