/// Настройки: PilotApp.swift, LanguageSettings.swift, KeymapSettings.swift.
extension English {
    static let settings: [(String, String)] = [
        ("Общие", "General"),
        ("Сочетания клавиш", "Key Bindings"),
        // Язык
        ("Язык интерфейса", "Interface language"),
        ("Как в системе — %@", "System default — %@"),
        ("Системные меню и диалоги macOS сменят язык после перезапуска Pilot.",
         "Standard macOS menus and dialogs switch language after Pilot restarts."),
        // Сочетания клавиш
        ("Команда или сочетание", "Command or shortcut"),
        ("Сбросить всё", "Reset All"),
        ("Показать keybindings.json в Finder — его можно править руками и носить с собой",
         "Show keybindings.json in Finder — you can edit it by hand and take it with you"),
        ("⇧⇧, ⌃Tab, ⌃- / ⌃⇧- и боковые кнопки мыши работают всегда, в дополнение к назначенному.",
         "⇧⇧, ⌃Tab, ⌃- / ⌃⇧- and the side mouse buttons always work, in addition to what is assigned."),
        ("«%@»", "“%@”"),
        ("То же сочетание у %@ — сработает одно из них", "%@ has the same shortcut — only one of them will fire"),
        ("Нажмите сочетание…", "Press shortcut…"),
        ("Клик — записать новое сочетание; ⌫ — убрать, ⎋ — отменить",
         "Click to record a new shortcut; ⌫ removes it, ⎋ cancels"),
        ("без сочетания", "no shortcut"),
        ("Вернуть: %@", "Restore: %@"),
        ("%@ уже у «%@»", "%1$@ is already used by “%2$@”"),
        ("Забрать сочетание у той команды или оставить у обеих? С двумя сработает только одна.",
         "Take the shortcut from that command or keep it on both? With two, only one will fire."),
        ("Забрать", "Take It"),
        ("Оставить у обеих", "Keep on Both"),
        ("Отмена", "Cancel"),

        // Слитые ветки: настройки
        ("Оформление", "Appearance"),
        ("Импорт из Rider…", "Import from Rider…"),
        ("Сочетания, размер шрифта и счётчики использований из settings.zip или папки настроек Rider", "Shortcuts, font size and usage counters from a Rider settings.zip or settings folder"),
        ("Окно", "Window"),
        ("Верхняя панель", "Top Bar"),
        ("Обычная", "Regular"),
        ("Компактная", "Compact"),
        ("Путь к файлу над редактором", "File path above the editor"),
        ("Вкладки проектов", "Project tabs"),
        ("Проекты открываются вкладками одного окна; полоса с названиями — когда их больше одного. Выключено — каждый проект в своём окне, а вторая половина пары — вкладкой по своей кнопке.", "Projects open as tabs of one window; the bar with their names appears when there’s more than one. Off — each project gets its own window, and the other half of a pair opens as a tab from its button."),
        ("Кнопки на панели", "Toolbar buttons"),
        ("Настроить…", "Customize…"),
        // Настройки → Кэши: CacheSettingsView.swift, CacheStore.swift
        ("Кэши", "Caches"),
        ("Кэши Pilot: %@", "Pilot caches: %@"),
        ("Ещё %@ — история правок", "Plus %@ of local history"),
        ("Считаю…", "Calculating…"),
        ("Пересчитать", "Recalculate"),
        ("Выключенный кэш Pilot не пишет и не читает: то же строится заново при каждом открытии проекта — дольше, но так же верно. Разбор файлов, сборки и архив jadx открытые проекты перестанут писать, когда их откроют заново.",
         "Pilot neither writes nor reads a cache that is turned off: the same is rebuilt every time a project opens — slower, but just as correct. Open projects stop writing parsed files, assemblies and the jadx archive once they are reopened."),
        ("Хранить на диске", "Keep on disk"),
        ("Хранится вместе с видом «%@» — сначала включите его", "Kept together with “%@” — turn that on first"),
        ("Удалить с диска: %@", "Remove from disk: %@"),
        ("Удалять нечего", "Nothing to remove"),
        ("не хранится", "not kept"),
        // Виды кэша: CacheStore.swift
        ("Компиляция Rustlyn", "Rustlyn compilation"),
        ("Разбор файлов Rustlyn", "Rustlyn parsed files"),
        ("Индекс объявлений", "Declaration index"),
        ("Список файлов", "File list"),
        ("GUID ассетов Unity", "Unity asset GUIDs"),
        ("Типы из сборок", "Types from assemblies"),
        ("Разобранные сборки .NET", "Parsed .NET assemblies"),
        ("Архив классов jadx", "jadx class archive"),
        ("Остатки прежних версий", "Leftovers from earlier versions"),
        ("Старые версии сервера Copilot", "Old Copilot server versions"),
        ("⌘B, ссылки и подсказки работают сразу при открытии проекта. Без неё — только после компиляции.",
         "⌘B, usages and completion work as soon as a project opens. Without it — only once it has compiled."),
        ("Открытие проекта читает разобранные файлы C#, а не разбирает их заново. Без него — разбор всех файлов, и компиляция не хранится.",
         "Opening a project reads parsed C# files instead of parsing them again. Without it — every file is parsed, and the compilation isn’t kept."),
        ("Навигатор и ⇧⇧ по типам — с первой секунды; разбираются только изменённые файлы. Без него — весь проект при каждом открытии.",
         "The navigator and ⇧⇧ for types work from the first second; only changed files are parsed. Without it — the whole project on every opening."),
        ("Дерево и ⌘P — сразу при открытии. Без него — после обхода папки, а вторая половина пары ищется, только пока открыто её окно.",
         "The file tree and ⌘P work right away. Without it — after the folder is walked, and the other half of a pair is searched only while its window is open."),
        ("Ссылки на ассеты подписаны с первой секунды, перечитываются только изменённые .meta. Без него — все .meta при каждом открытии.",
         "Asset references are labelled from the first second; only changed .meta files are read again. Without it — every .meta on every opening."),
        ("⇧⇧ и ⌘B по типам движка и плагинов без чтения сотен сборок. Без него — сборки читаются при каждом открытии.",
         "⇧⇧ and ⌘B on engine and plugin types without reading hundreds of assemblies. Without it — the assemblies are read on every opening."),
        ("Декомпилированные сборки, общие для всех проектов: UnityEditor разбирается один раз. Без них — при каждом открытии проекта.",
         "Decompiled assemblies shared by all projects: UnityEditor is parsed once. Without them — every time a project opens."),
        ("Ускоряет запуск декомпилятора Java. Без него каждый запуск дольше.",
         "Makes the Java decompiler start faster. Without it every start takes longer."),
        ("Сборки, разобранные в папках проектов до того, как их кэш стал общим. Не используются.",
         "Assemblies parsed into project folders before their cache became shared. Not used."),
        ("Скачанные раньше; нужна только текущая версия.", "Downloaded earlier; only the current version is needed."),
        ("Скачанные раньше: %@; нужна только текущая.", "Downloaded earlier: %@; only the current one is needed."),
        ("Проекты, которых Pilot не помнит (%@)", "Projects Pilot no longer remembers (%@)"),
        ("Виды кэша", "Cache Types"),
        // Очистка
        ("Удалять кэши проектов, которые не открывали", "Remove caches of projects not opened for"),
        ("Никогда", "Never"),
        ("30 дней", "30 days"),
        ("90 дней", "90 days"),
        ("180 дней", "180 days"),
        ("Удалить устаревшие (%@)", "Remove Stale (%@)"),
        ("Проекты, которых нет на диске или которые не открывали %@ дней, и остатки прежних версий",
         "Projects that are gone from disk or were not opened for %@ days, and leftovers from earlier versions"),
        ("Очистить все кэши…", "Clear All Caches…"),
        ("Очистить все кэши (%@)?", "Clear all caches (%@)?"),
        ("Проекты соберут кэши заново при следующем открытии — первый раз это дольше обычного. История правок останется.", "Projects rebuild their caches the next time they open, which takes longer that first time. Local history stays."),
        // Выключили вид — удалить накопленное?
        ("Удалить «%@» с диска (%@)?", "Remove “%@” from disk (%@)?"),
        ("Оставить", "Keep"),
        ("Pilot больше его не пишет. Оставленное пригодится, если кэш снова включить.",
         "Pilot no longer writes it. What you keep will be used if the cache is turned back on."),
        ("Вместе с ним перестаёт храниться «%@».", "Along with it, “%@” is no longer kept."),
        ("Ещё %@ держат открытые проекты — это можно будет удалить после их закрытия.",
         "Open projects hold another %@ — it can be removed once they are closed."),
        ("Открытые проекты перестанут его писать, когда их откроют заново.", "Open projects stop writing it once they are reopened."),
        // Проекты
        ("Кэш ускоряет открытие проекта, поиск и навигацию. Удалённый кэш проект соберёт заново, когда его откроют. То, что открытый проект держит в работе, удаляется после его закрытия.",
         "Caches speed up opening a project, search and navigation. A removed cache is rebuilt the next time the project is opened. What an open project is using can be removed once it is closed."),
        ("Кэшей проектов нет", "No project caches"),
        ("Удалить то, что проект не держит в работе: %@", "Remove what the project isn’t using: %@"),
        ("Проект открыт — закройте его, чтобы удалить", "The project is open — close it to remove"),
        ("нет на диске", "gone from disk"),
        ("путь неизвестен", "path unknown"),
        ("изменён %@", "modified %@"),
        // История правок
        ("История правок", "Local History"),
        ("Не кэш: прежние версии файлов, которые Pilot сохранял при правке. Удалённую историю не вернуть.", "Not a cache: earlier versions of files Pilot kept while you edited. Removed history cannot be restored."),
        ("Удалить историю правок «%@»?", "Remove local history of “%@”?"),
        ("Удалить", "Remove"),
        ("Прежние версии файлов этого проекта пропадут насовсем.", "Earlier versions of this project's files will be gone for good."),
    ]
}
