/// Окно редактора: навигатор, палитра, вкладки, строка состояния, ревью.
extension English {
    static let ui: [(String, String)] = [
        // Числа
        ("конфликт|конфликта|конфликтов", "conflict|conflicts"),
        ("строка|строки|строк", "line|lines"),
        ("объявление|объявления|объявлений", "declaration|declarations"),

        // ConflictViews.swift
        ("другая ветка", "other branch"),
        ("Текущее", "Current"),
        ("Оставить текущее (%@) · ⌃⌥⌘←", "Keep current (%@) · ⌃⌥⌘←"),
        ("Входящее", "Incoming"),
        ("Взять входящее (%@) · ⌃⌥⌘→", "Take incoming (%@) · ⌃⌥⌘→"),
        ("Оба", "Both"),
        ("Оставить оба варианта: сначала текущее, потом входящее", "Keep both: current first, then incoming"),
        ("База", "Base"),
        ("Вернуть общего предка — отбросить обе стороны", "Restore the common ancestor — discard both sides"),
        ("Конфликтов в файле не осталось", "No conflicts left in this file"),
        ("Сохранить и отметить решённым", "Save and Mark Resolved"),
        ("Сохранить файл и выполнить git add — для git это и значит «конфликт решён»",
         "Save the file and run git add — that is what “resolved” means to git"),
        ("Конфликт %@ из %@", "Conflict %@ of %@"),
        ("Все текущие", "All Current"),
        ("Во всех конфликтах файла оставить текущее", "Keep current in every conflict in this file"),
        ("Все входящие", "All Incoming"),
        ("Во всех конфликтах файла взять входящее", "Take incoming in every conflict in this file"),

        // FileTreeView.swift
        ("Скопировать путь в иерархии", "Copy Hierarchy Path"),
        ("Показать в Finder", "Show in Finder"),
        ("Скопировать путь", "Copy Path"),
        ("Скопировать полный путь", "Copy Full Path"),
        ("%@ — вложенный префаб", "%@ — nested prefab"),

        // JumpBar.swift
        ("Нет структуры", "No Structure"),
        ("Нет выделения", "No Selection"),
        ("… и ещё %@", "… and %@ more"),
        ("Есть несохранённые изменения (⌘S)", "Unsaved changes (⌘S)"),

        // NavigatorView.swift
        ("Папка не открыта", "No folder open"),
        ("Индексация…", "Indexing…"),
        ("Ничего не найдено", "Nothing found"),
        ("Поиск мерж-реквестов", "Search merge requests"),
        ("Фильтр", "Filter"),
        ("Слова из названия, ветки, меток или имени; !123 — номер, @логин — автор или ревьюер. Слитые и закрытые ищутся в GitLab.",
         "Words from the title, branch, labels or name; !123 — number, @login — author or reviewer. Merged and closed ones are searched in GitLab."),
        ("В этом файле объявлений не найдено", "No declarations found in this file"),
        ("Откройте файл, чтобы увидеть его структуру", "Open a file to see its structure"),

        // ReviewViews.swift
        ("Повторить", "Retry"),
        ("Подключить GitLab…", "Connect GitLab…"),
        ("Ещё в GitLab", "More in GitLab"),
        ("Открытых мерж-реквестов нет", "No open merge requests"),
        ("Обновить список", "Refresh list"),
        ("Сменить токен…", "Change Token…"),
        ("Отключить GitLab", "Disconnect GitLab"),
        ("Черновик", "Draft"),
        ("Слит", "Merged"),
        ("Закрыт", "Closed"),
        ("Заблокирован", "Locked"),
        ("Файлы · просмотрено %@ из %@", "Files · %@ of %@ viewed"),
        ("Обсуждение", "Discussion"),
        ("Комментарий к мерж-реквесту…", "Comment on the merge request…"),
        ("Все мерж-реквесты", "All Merge Requests"),
        ("Обновить треды и апрувы", "Refresh threads and approvals"),
        ("Открыть в GitLab", "Open in GitLab"),
        ("Апрувы: %@", "Approved by: %@"),
        ("Просмотрен", "Viewed"),
        ("Апрувнуто", "Approved"),
        ("Апрув", "Approve"),
        ("Отозвать апрув", "Revoke approval"),
        ("Одобрить эту версию MR", "Approve this version of the MR"),
        ("Файл удалён", "File deleted"),
        ("Дифф слишком большой", "Diff too large"),
        ("%@ из %@", "%@ of %@"),
        ("Отметить файл просмотренным", "Mark file as viewed"),
        ("рабочая копия", "working copy"),
        ("Закончить ревью", "Finish review"),
        ("Комментарий к строке…", "Comment on this line…"),
        ("Новый тред к строке…", "New thread on this line…"),
        ("Было:", "Was:"),
        ("Было (%@ строк):", "Was (%@ lines):"),
        ("… ещё %@", "… %@ more"),
        ("К предыдущей версии MR — строка могла сдвинуться", "On an earlier version of the MR — the line may have moved"),
        ("Ответить", "Reply"),
        ("Открыть снова", "Reopen"),
        ("Решить", "Resolve"),
        ("Решён", "Resolved"),
        ("Ответ…", "Reply…"),
        ("Отправить", "Send"),
        ("Подключение к GitLab", "Connect to GitLab"),
        ("Pilot ходит в API GitLab с вашим Personal Access Token. Токен хранится в связке ключей macOS и уходит только на указанный хост. Для комментариев и апрувов нужны права api.",
         "Pilot calls the GitLab API with your personal access token. The token is stored in the macOS keychain and is sent only to the host you specify. Comments and approvals need the api scope."),
        ("Хост", "Host"),
        ("Токен", "Token"),
        ("Создать токен в GitLab ↗", "Create a token in GitLab ↗"),
        ("Подключить", "Connect"),

        // PalettePreview.swift
        ("Пустой файл", "Empty file"),
        ("стр. %@ из %@", "line %@ of %@"),

        // PaletteView.swift
        ("Скрыть предпросмотр", "Hide preview"),
        ("Показать предпросмотр", "Show preview"),
        ("Где используется %@", "Usages of %@"),
        ("Всё сразу, по смыслу запроса (⌘P, ⇧⇧)", "Everything at once, ranked by the query (⌘P, ⇧⇧)"),
        ("Только файлы (⌘P ещё раз)", "Files only (⌘P again)"),
        ("Только типы, в том числе из сборок (⇧⇧ ещё раз)", "Types only, including ones from assemblies (⇧⇧ again)"),
        ("Типы и их члены (⌘T)", "Types and their members (⌘T)"),
        ("Текст в файлах проекта (⇧⌘F)", "Text in project files (⇧⌘F)"),
        ("Файлов в индексе", "Files in the index"),
        ("Типов в индексе", "Types in the index"),
        ("Ищу…", "Searching…"),
        ("Использований не найдено", "No usages found"),
        ("Собираю объявления проекта…", "Collecting project declarations…"),
        ("Ни наследников, ни переопределений не нашлось", "No subclasses or overrides found"),
        ("Сначала откройте файл", "Open a file first"),
        ("Проект не под git", "The project is not under git"),
        ("Изменений нет — всё закоммичено", "No changes — everything is committed"),
        ("Здесь будут места, где вы были и что правили", "Places you visited and edited will appear here"),
        ("На %@ не ссылается ни одна сцена, префаб или ассет", "No scene, prefab or asset references %@"),
        ("Собираю типы проекта…", "Collecting project types…"),
        ("Начните вводить имя типа — можно заглавными: USvc → UserService",
         "Start typing a type name — capitals work too: USvc → UserService"),
        ("Собираю символы проекта…", "Collecting project symbols…"),
        ("Начните вводить имя символа", "Start typing a symbol name"),
        ("Начните вводить текст — ищу по всем файлам проекта", "Start typing — searches all project files"),

        // RootView.swift
        ("⇧⌘R — где используется этот ассет  ·  ⌃⌘M — открыть его .meta",
         "⇧⌘R — usages of this asset  ·  ⌃⌘M — open its .meta"),
        ("Нет открытого файла", "No File Open"),
        ("Перейти к файлу", "Go to File"),
        ("Найти класс", "Find Class"),
        ("Поиск", "Search"),
        ("Файлы, типы, символы и текст — одним поиском (⌘P, ⇧⇧)", "Files, types, symbols and text in one search (⌘P, ⇧⇧)"),
        ("Исходник", "Source"),
        ("Просмотр", "Preview"),
        ("Показать исходник (⇧⌘V)", "Show source (⇧⌘V)"),
        ("Показать свёрстанным (⇧⌘V)", "Show rendered (⇧⌘V)"),
        ("Ассетов с GUID: %@.", "Assets with a GUID: %@."),
        ("Собираю GUID ассетов…", "Collecting asset GUIDs…"),
        ("⌘B или ⌘+клик по GUID — открыть ассет, по fileID — перейти к объекту.\n⇧⌘R — где используется открытый ассет. ⌃⌘M — ассет ↔ .meta.\n⌥⌘0 — инспектор сцены, префаба или ассета.\n.meta скрыты из поиска и дерева.",
         "⌘B or ⌘-click on a GUID opens the asset, on a fileID goes to the object.\n⇧⌘R — usages of the open asset. ⌃⌘M — asset ↔ .meta.\n⌥⌘0 — inspector for the scene, prefab or asset.\n.meta files are hidden from search and the tree."),
        ("Ветка %@", "Branch %@"),
        ("HEAD отсоединён: %@", "Detached HEAD: %@"),
        ("Впереди на %@, позади на %@ коммитов", "%@ commits ahead, %@ behind"),
        ("Изменено файлов: %@ — ⌃⇧G", "Changed files: %@ — ⌃⇧G"),
        ("Изменений нет", "No changes"),
        ("Нет открытого проекта", "No project open"),
        ("Готово", "Ready"),
        ("Ошибки в этом файле. F2 — к следующей, ⇧F2 — к предыдущей.", "Errors in this file. F2 — next, ⇧F2 — previous."),
        ("Индекс", "Index"),
        ("Собираю объявления проекта для ⌘B, ⌘T и ⌘R.", "Collecting project declarations for ⌘B, ⌘T and ⌘R."),
        ("⌘B, ⌘T и ⌘R отвечают по быстрому индексу: %@. Это приближение — без перегрузок и типов из лямбд. Когда Rustlyn скомпилирует проект, ⌘B и ⌘R по C# незаметно перейдут на него.",
         "⌘B, ⌘T and ⌘R use the fast index: %@. It is an approximation — no overloads or lambda types. Once Rustlyn compiles the project, ⌘B and ⌘R in C# switch to it seamlessly."),
        ("Декомпиляция %@", "Decompiling %@"),
        ("Собираю текст %@ из метаданных. Откроется, как только будет готов.", "Rebuilding the source of %@ from metadata. It opens as soon as it is ready."),
        ("Rustlyn компилирует проект. Пока ⌘B отвечает индекс объявлений, а ⌘R ищет по тексту.",
         "Rustlyn is compiling the project. Meanwhile ⌘B uses the declaration index and ⌘R searches text."),
        ("Rustlyn перекомпилирует проект после правки. Пока отвечает прошлая компиляция.",
         "Rustlyn is recompiling the project after an edit. The previous compilation answers meanwhile."),
        ("Проект скомпилирован: %@.\n⌘B или ⌘+клик — объявление, ⌘R — использования, дополнение — по типам.",
         "Project compiled: %@.\n⌘B or ⌘-click — declaration, ⌘R — usages, type-aware completion."),
        ("%@: %@. Просмотр и поиск работают уже сейчас.", "%@: %@. Browsing and search already work."),
        ("Переход к определению: ⌘B или ⌘+клик. Символы: ⌘T. Использования: ⌘R.",
         "Go to definition: ⌘B or ⌘-click. Symbols: ⌘T. Usages: ⌘R."),
        ("Языковой сервер не поднялся:\n%@", "The language server failed to start:\n%@"),
        ("Строка: %@   Столбец: %@", "Line: %@   Column: %@"),
        ("Не закоммичено", "Not committed"),
        ("Строка отличается от HEAD", "The line differs from HEAD"),
        ("Скопировать хэш коммита", "Copy Commit Hash"),

        // TabBar.swift
        ("Оставить вкладку открытой", "Keep Tab Open"),
        ("Закрыть вкладки справа", "Close Tabs to the Right"),
        ("Объявления из сборки — только для чтения", "Declarations from an assembly — read-only"),
        ("%@: IL из метаданных — только для чтения", "%@: IL from metadata — read-only"),
        ("Декомпилировано jadx — только для чтения", "Decompiled by jadx — read-only"),
        ("Версия из мерж-реквеста — только для чтения", "Version from the merge request — read-only"),
        ("%@\nВременная вкладка — двойной клик оставит её открытой", "%@\nPreview tab — double-click to keep it open"),
        ("временная", "preview"),
        ("не сохранено", "unsaved"),
        ("%@\nС ⌥ — закрыть все остальные", "%@\nWith ⌥ — close all others"),

        // StartView.swift
        ("Откройте папку проекта, чтобы начать", "Open a project folder to get started"),
        ("Мгновенный просмотрщик кода", "An instant code viewer"),
        ("Недавние", "Recent"),
        ("Убрать из списка", "Remove from List"),
        ("↑↓ выбрать · ⏎ открыть · ⌘1–9", "↑↓ select · ⏎ open · ⌘1–9"),

        // Слитые ветки: палитра пары
        ("Во второй половине пары ничего не нашлось", "Nothing found in the other half of the pair"),
        ("Датаграммы клиента и сервера сходятся", "Client and server datagrams match"),
        ("Зеркальные файлы одинаковы в обеих половинах", "Mirrored files are identical in both halves"),
        ("Статус", "Status"),
        ("Проект и ветка", "Project and Branch"),
        ("Цель", "Target"),
        ("Перезапустить «%@»", "Restart “%@”"),
        // Граф значения
        ("«Кто пишет» — раскрыть · двойной клик — к коду · щипок — масштаб", "“Who writes” to expand · double-click for code · pinch to zoom"),
        ("В %@ у %@ нет поля %@", "In %@, %@ has no field %@"),
        ("Весь метод", "Whole Method"),
        ("Граф значения", "Value Graph"),
        ("Граф значения — для C#, когда Rustlyn скомпилировал проект", "The value graph is for C#, once Rustlyn has compiled the project"),
        ("Записей не нашлось — значение задают в объявлении или через рефлексию", "No writes found — the value is set in its declaration or via reflection"),
        ("Ищу записи…", "Looking for writes…"),
        ("Кто пишет", "Who Writes"),
        ("Откройте %@ — граф идёт по его компилятору", "Open %@ — the graph follows its compiler"),
        ("Откройте %@, чтобы пройти дальше", "Open %@ to go further"),
        ("Открыть в редакторе", "Open in Editor"),
        ("Откуда берётся %@", "Where %@ comes from"),
        ("Откуда: %@", "Source of %@"),
        ("Сеть: %@", "Network: %@"),
        ("меняет прежнее значение", "changes the previous value"),
        ("параметр %@", "parameter of %@"),
        ("приходит из %@", "comes from %@"),
        ("через %@", "via %@"),
        ("Add — компонент появляется", "Add — the component appears"),
        ("Remove — компонент убирают", "Remove — the component is taken off"),
        ("Set — компонент появляется или обновляется", "Set — the component appears or is updated"),
        ("Set, Add и Remove этого компонента не нашлись", "No Set, Add or Remove of this component found"),
        ("return не нашёлся — метод без тела или из сборки", "No return found — the method has no body or comes from an assembly"),
        ("Вызовов не нашлось — метод зовёт движок или рефлексия", "No calls found — the engine or reflection calls the method"),
        ("Где её шлют", "Where It’s Sent"),
        ("Где появляется и убирается", "Where It Appears and Goes"),
        ("Кто передаёт", "Who Passes It"),
        ("Отправок не нашлось", "No sends found"),
        ("Поставьте курсор на поле, свойство или компонент — граф покажет, откуда они берутся", "Put the cursor on a field, property or component — the graph shows where it comes from"),
        ("Пришла %@", "%@ arrived"),
        ("У проекта нет пары — отправок не найти", "The project has no pair — sends can’t be found"),
        ("Фильтр %@", "Filter %@"),
        ("Что возвращает", "What It Returns"),
        ("без %@", "without %@"),
        ("возвращает", "returns"),
        ("вызов · %@", "call · %@"),
        ("вызывает %@", "calls %@"),
        ("компилятор не узнал имя", "the compiler didn’t recognize the name"),
        ("компонент · %@", "component · %@"),
        ("найдено по имени — может быть неточно", "found by name — may be imprecise"),
        ("отправка %@", "sends %@"),
        ("цикл по %@<%@>", "loop over %@<%@>"),
        ("Показать всё", "Show All"),
    ]
}
