/// Консоль Unity: Editor.log в Pilot.
extension English {
    static let unity: [(String, String)] = [
        // PilotApp.swift, Keymap.swift, RootView.swift
        ("Консоль Unity", "Unity Console"),
        ("Клик — консоль Unity", "Click for the Unity console"),

        // UnityHotReload.swift, UnityHotReloadTools.swift
        ("Горячая перезагрузка: включить", "Hot Reload: Turn On"),
        ("Горячая перезагрузка: выключить", "Hot Reload: Turn Off"),
        ("Горячая перезагрузка: %@ (выключить)", "Hot Reload: %@ (turn off)"),
        ("Горячая перезагрузка: включить (%@)", "Hot Reload: Turn On (%@)"),
        ("Откройте в Pilot саму папку Unity-проекта", "open the Unity project folder itself in Pilot"),
        ("Unity компилирует пробу — переключитесь на Unity", "Unity compiles the probe — switch to Unity"),
        ("Unity не скомпилировала пробу: переключитесь на Unity и включите снова", "Unity did not compile the probe: switch to Unity and turn it on again"),
        ("Собираю pilotpatch…", "building pilotpatch…"),
        ("Сначала откройте проект в Unity", "open the project in Unity first"),
        ("Готовлю инструменты…", "preparing tools…"),
        ("Генераторы и сборка целиком…", "generators and a whole build…"),
        ("Unity перезагружается на сборке Pilot…", "Unity reloads on Pilot’s build…"),
        ("Собираю %@…", "building %@…"),
        ("Собираю PilotRuntime…", "building PilotRuntime…"),

        // UnityConsoleView.swift
        ("Unity ещё не писала Editor.log", "Unity hasn’t written Editor.log yet"),
        ("Ошибки и исключения", "Errors and exceptions"),
        ("Предупреждения", "Warnings"),
        ("Служебный вывод редактора", "Editor’s own output"),
        ("Свернуть повторы", "Collapse"),
        ("Одинаковые сообщения — одной строкой со счётчиком", "Show identical messages as one row with a count"),
        ("Очистить", "Clear"),
        ("Скрыть консоль Unity", "Hide the Unity Console"),
        ("Скопировать", "Copy"),
        ("Сообщений пока нет", "No messages yet"),
        ("Всё скрыто фильтрами", "Everything is hidden by filters"),
        ("Выберите сообщение — здесь будет стек; двойной клик — к месту в коде",
         "Select a message to see its stack; double-click to go to the code"),
        ("Editor.log сейчас пишет другой проект", "Editor.log is being written by another project"),
        ("Показать всё равно", "Show Anyway"),
        // Сгенерированный код: UnityGenerators.swift, Workspace+Generated.swift
        ("Сгенерированный код", "Generated Code"),
        ("Сгенерированный файл…", "Generated file…"),
        ("Что генераторы исходников написали для типов этого файла", "What source generators wrote for the types in this file"),
        ("Сгенерированный код есть только у Unity-проекта", "Generated code is only available in a Unity project"),
        ("Сначала откройте файл C#", "Open a C# file first"),
        ("Не найден редактор Unity %@", "Unity editor %@ not found"),
        ("Не найден компилятор Unity в %@", "Unity's compiler not found in %@"),
        ("Файл не из Unity-проекта", "The file is not in the Unity project"),
        ("Ищу сборку %@…", "Finding the assembly of %@…"),
        ("Генераторы работают над %@…", "Running generators on %@…"),
        ("Unity ещё не компилировала %@ — откройте проект в Unity", "Unity has not compiled %@ yet — open the project in Unity"),
        ("Для типов этого файла генераторы ничего не написали", "Generators wrote nothing for the types in this file"),
        ("Для типов этого файла генераторы ничего не написали (всего в %@: %@)", "Generators wrote nothing for the types in this file (%@ has %@ in total)"),
        ("Не удалось прочитать %@", "Couldn't read %@"),
        ("Собрано в %@ — исходники с тех пор не менялись", "Generated at %@ — the sources haven't changed since"),
        ("Собрано в %@, исходники с тех пор менялись — обновляю…", "Generated at %@; the sources have changed since — refreshing…"),
        ("Собрано в %@ и может быть устаревшим: %@", "Generated at %@ and may be outdated: %@"),
        ("Собрано в %@, исходники с тех пор менялись", "Generated at %@; the sources have changed since"),
        ("Обновлено в %@", "Refreshed at %@"),
    ]
}
