/// Самообновление: Updater.swift, UpdateBar.swift, раздел в настройках.
extension English {
    static let update: [(String, String)] = [
        // Меню и настройки
        ("Проверить обновления…", "Check for Updates…"),
        ("Проверять обновления автоматически", "Check for updates automatically"),
        ("Версия %@", "Version %@"),
        ("Проверить сейчас", "Check Now"),
        // Updater.swift
        ("Не удалось проверить обновления", "Couldn’t check for updates"),
        ("Обновлений нет", "No Updates"),
        ("Pilot %@ — последняя версия.", "Pilot %@ is the latest version."),
        ("Это сборка из исходников — новую версию скачайте со страницы релиза",
         "This is a build from source — download the new version from the release page"),
        ("Перенесите Pilot в «Программы» — оттуда он сможет обновляться сам",
         "Move Pilot to Applications so it can update itself"),
        ("Нет прав на запись в папку, где лежит Pilot", "No permission to write to the folder Pilot is in"),
        ("Сервер обновлений ответил %@", "The update server responded %@"),
        ("Нужен токен GitLab для %@", "A GitLab token for %@ is needed"),
        ("Токен GitLab для %@", "GitLab Token for %@"),
        ("Обновления этой сборки Pilot лежат в GitLab. Нужен личный токен с правом read_api — тот же, что для ревью мерж-реквестов.",
         "Updates for this Pilot build are published in GitLab. It needs a personal access token with the read_api scope — the same one used for merge request reviews."),
        ("Не удалось сохранить токен", "Couldn’t save the token"),
        ("Обновления этой сборки — в GitLab %@: нужен токен", "Updates for this build are in GitLab %@: a token is needed"),
        ("Ввести токен…", "Enter Token…"),
        ("Скрыть до следующего запуска", "Hide until next launch"),
        ("Не удалось скачать обновление: %@", "Couldn’t download the update: %@"),
        ("Не удалось распаковать обновление", "Couldn’t unpack the update"),
        ("Подпись обновления не совпала с подписью Pilot — не устанавливаю",
         "The update’s signature doesn’t match Pilot’s — not installing"),
        ("В архиве не та версия: %@", "The archive contains a different version: %@"),
        // UpdateBar.swift
        ("Доступна новая версия Pilot %@ — у вас %@", "Pilot %@ is available — you have %@"),
        ("Скачиваю Pilot %@…", "Downloading Pilot %@…"),
        ("Устанавливаю Pilot %@…", "Installing Pilot %@…"),
        ("Pilot %@ установлен — перезапустите, чтобы перейти на него",
         "Pilot %@ is installed — restart to switch to it"),
        ("Не удалось обновить: %@", "Update failed: %@"),
        ("Что нового", "What’s New"),
        ("Скачать", "Download"),
        ("Обновить сейчас", "Update Now"),
        ("Перезапустить", "Restart"),
        ("Скачать вручную", "Download Manually"),
        ("Не напоминать об этой версии", "Don’t remind me about this version"),
    ]
}
